//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.Tables
{
public class tblT_USER_CREDIT
{
public const string _Name = "T_USER_CREDIT";
public const string _Caption = "T_ USER_ CREDIT";

public class colUSD_COMPLETED_TRANSACTION_ID
{
public const string _Name = "USD_COMPLETED_TRANSACTION_ID";
public const string _Caption = "USD_ COMPLETED_ TRANSACTION_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_COMPLETED_TRANSACTION_ID";
public const string _BindDataReader = "[USD_COMPLETED_TRANSACTION_ID]";
}
public class colUSD_CREATION_DATETIME
{
public const string _Name = "USD_CREATION_DATETIME";
public const string _Caption = "USD_ CREATION_ DATETIME";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.DateTime;
public const Int32 _Length = 8;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_CREATION_DATETIME";
public const string _BindDataReader = "[USD_CREATION_DATETIME]";
}
public class colUSD_CREDIT_TYPE_CODE
{
public const string _Name = "USD_CREDIT_TYPE_CODE";
public const string _Caption = "USD_ CREDIT_ TYPE_ CODE";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_CREDIT_TYPE_CODE";
public const string _BindDataReader = "[USD_CREDIT_TYPE_CODE]";
}
public class colUSD_CREDITS
{
public const string _Name = "USD_CREDITS";
public const string _Caption = "USD_ CREDITS";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_CREDITS";
public const string _BindDataReader = "[USD_CREDITS]";
}
public class colUSD_ID
{
public const string _Name = "USD_ID";
public const string _Caption = "USD_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_ID";
public const string _BindDataReader = "[USD_ID]";
}
public class colUSD_PAYED_FOR_USER_ID
{
public const string _Name = "USD_PAYED_FOR_USER_ID";
public const string _Caption = "USD_ PAYED_ FOR_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_PAYED_FOR_USER_ID";
public const string _BindDataReader = "[USD_PAYED_FOR_USER_ID]";
}
public class colUSD_PAYER_USER_ID
{
public const string _Name = "USD_PAYER_USER_ID";
public const string _Caption = "USD_ PAYER_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_PAYER_USER_ID";
public const string _BindDataReader = "[USD_PAYER_USER_ID]";
}
public class colUSD_PRESENT_CODE
{
public const string _Name = "USD_PRESENT_CODE";
public const string _Caption = "USD_ PRESENT_ CODE";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_PRESENT_CODE";
public const string _BindDataReader = "[USD_PRESENT_CODE]";
}
public class colUSD_REFUNDED_TRANSACTION_ID
{
public const string _Name = "USD_REFUNDED_TRANSACTION_ID";
public const string _Caption = "USD_ REFUNDED_ TRANSACTION_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_REFUNDED_TRANSACTION_ID";
public const string _BindDataReader = "[USD_REFUNDED_TRANSACTION_ID]";
}
public class colUSD_USER_ID
{
public const string _Name = "USD_USER_ID";
public const string _Caption = "USD_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_CREDIT";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_CREDIT.DefaultView.[0].USD_USER_ID";
public const string _BindDataReader = "[USD_USER_ID]";
}
public class idcUSD_ID : colUSD_ID {}
public class idxIX_T_USER_CREDIT_USD_USER_ID
{
public const string _Name = "IX_T_USER_CREDIT_USD_USER_ID";
public const string _Caption = "IX_ T_ USER_ CREDIT_ USD_ USER_ ID";
public const string _ParentName = "T_USER_CREDIT";
public const bool _IsPrimaryKey = false;

public class ixcUSD_USER_ID : colUSD_USER_ID {}
}
public class idxPK_T_USER_CREDIT
{
public const string _Name = "PK_T_USER_CREDIT";
public const string _Caption = "PK_ T_ USER_ CREDIT";
public const string _ParentName = "T_USER_CREDIT";
public const bool _IsPrimaryKey = true;

public class ixcUSD_ID : colUSD_ID {}
}
public class pkxPK_T_USER_CREDIT : idxPK_T_USER_CREDIT {}
}
}
