//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.Tables
{
public class tblT_USER_LIKE
{
public const string _Name = "T_USER_LIKE";
public const string _Caption = "T_ USER_ LIKE";

public class colUSK_FB_NAME
{
public const string _Name = "USK_FB_NAME";
public const string _Caption = "USK_ FB_ NAME";
public const string _Description = "";
public const string _ParentName = "T_USER_LIKE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LIKE.DefaultView.[0].USK_FB_NAME";
public const string _BindDataReader = "[USK_FB_NAME]";
}
public class colUSK_FB_OBJECT_ID
{
public const string _Name = "USK_FB_OBJECT_ID";
public const string _Caption = "USK_ FB_ OBJECT_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_LIKE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LIKE.DefaultView.[0].USK_FB_OBJECT_ID";
public const string _BindDataReader = "[USK_FB_OBJECT_ID]";
}
public class colUSK_FB_OBJECT_URL
{
public const string _Name = "USK_FB_OBJECT_URL";
public const string _Caption = "USK_ FB_ OBJECT_ URL";
public const string _Description = "";
public const string _ParentName = "T_USER_LIKE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LIKE.DefaultView.[0].USK_FB_OBJECT_URL";
public const string _BindDataReader = "[USK_FB_OBJECT_URL]";
}
public class colUSK_FB_PIC_URL
{
public const string _Name = "USK_FB_PIC_URL";
public const string _Caption = "USK_ FB_ PIC_ URL";
public const string _Description = "";
public const string _ParentName = "T_USER_LIKE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LIKE.DefaultView.[0].USK_FB_PIC_URL";
public const string _BindDataReader = "[USK_FB_PIC_URL]";
}
public class colUSK_FB_PICX_URL
{
public const string _Name = "USK_FB_PICX_URL";
public const string _Caption = "USK_ FB_ PICX_ URL";
public const string _Description = "";
public const string _ParentName = "T_USER_LIKE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LIKE.DefaultView.[0].USK_FB_PICX_URL";
public const string _BindDataReader = "[USK_FB_PICX_URL]";
}
public class colUSK_ID
{
public const string _Name = "USK_ID";
public const string _Caption = "USK_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_LIKE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_USER_LIKE.DefaultView.[0].USK_ID";
public const string _BindDataReader = "[USK_ID]";
}
public class colUSK_USER_ID
{
public const string _Name = "USK_USER_ID";
public const string _Caption = "USK_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_LIKE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LIKE.DefaultView.[0].USK_USER_ID";
public const string _BindDataReader = "[USK_USER_ID]";
}
public class idcUSK_ID : colUSK_ID {}
public class idxIX_T_USER_LIKE_USK_USER_ID
{
public const string _Name = "IX_T_USER_LIKE_USK_USER_ID";
public const string _Caption = "IX_ T_ USER_ LIKE_ USK_ USER_ ID";
public const string _ParentName = "T_USER_LIKE";
public const bool _IsPrimaryKey = false;

public class ixcUSK_USER_ID : colUSK_USER_ID {}
}
public class idxIX_T_USER_LIKE_USK_USER_ID_USK_FB_OBJECT_ID
{
public const string _Name = "IX_T_USER_LIKE_USK_USER_ID_USK_FB_OBJECT_ID";
public const string _Caption = "IX_ T_ USER_ LIKE_ USK_ USER_ ID_ USK_ FB_ OBJECT_ ID";
public const string _ParentName = "T_USER_LIKE";
public const bool _IsPrimaryKey = false;

public class ixcUSK_FB_OBJECT_ID : colUSK_FB_OBJECT_ID {}
public class ixcUSK_USER_ID : colUSK_USER_ID {}
}
public class idxPK_T_USER_LIKE
{
public const string _Name = "PK_T_USER_LIKE";
public const string _Caption = "PK_ T_ USER_ LIKE";
public const string _ParentName = "T_USER_LIKE";
public const bool _IsPrimaryKey = true;

public class ixcUSK_ID : colUSK_ID {}
}
public class pkxPK_T_USER_LIKE : idxPK_T_USER_LIKE {}
}
}
