//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.Tables
{
public class tblT_USER_COMM
{
public const string _Name = "T_USER_COMM";
public const string _Caption = "T_ USER_ COMM";

public class colUSC_COMM_TYPE_CODE
{
public const string _Name = "USC_COMM_TYPE_CODE";
public const string _Caption = "USC_ COMM_ TYPE_ CODE";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_COMM_TYPE_CODE";
public const string _BindDataReader = "[USC_COMM_TYPE_CODE]";
}
public class colUSC_GETTER_USER_ID
{
public const string _Name = "USC_GETTER_USER_ID";
public const string _Caption = "USC_ GETTER_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_GETTER_USER_ID";
public const string _BindDataReader = "[USC_GETTER_USER_ID]";
}
public class colUSC_ID
{
public const string _Name = "USC_ID";
public const string _Caption = "USC_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_ID";
public const string _BindDataReader = "[USC_ID]";
}
public class colUSC_IS_READ
{
public const string _Name = "USC_IS_READ";
public const string _Caption = "USC_ IS_ READ";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_IS_READ";
public const string _BindDataReader = "[USC_IS_READ]";
}
public class colUSC_PRESENT_CODE
{
public const string _Name = "USC_PRESENT_CODE";
public const string _Caption = "USC_ PRESENT_ CODE";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_PRESENT_CODE";
public const string _BindDataReader = "[USC_PRESENT_CODE]";
}
public class colUSC_SENDER_USER_ID
{
public const string _Name = "USC_SENDER_USER_ID";
public const string _Caption = "USC_ SENDER_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_SENDER_USER_ID";
public const string _BindDataReader = "[USC_SENDER_USER_ID]";
}
public class colUSC_SENT_DATETIME
{
public const string _Name = "USC_SENT_DATETIME";
public const string _Caption = "USC_ SENT_ DATETIME";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.DateTime;
public const Int32 _Length = 8;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_SENT_DATETIME";
public const string _BindDataReader = "[USC_SENT_DATETIME]";
}
public class colUSC_TEXT
{
public const string _Name = "USC_TEXT";
public const string _Caption = "USC_ TEXT";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_TEXT";
public const string _BindDataReader = "[USC_TEXT]";
}
public class colUSC_USER_ID
{
public const string _Name = "USC_USER_ID";
public const string _Caption = "USC_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_USER_ID";
public const string _BindDataReader = "[USC_USER_ID]";
}
public class colUSC_WINK_CODE
{
public const string _Name = "USC_WINK_CODE";
public const string _Caption = "USC_ WINK_ CODE";
public const string _Description = "";
public const string _ParentName = "T_USER_COMM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_COMM.DefaultView.[0].USC_WINK_CODE";
public const string _BindDataReader = "[USC_WINK_CODE]";
}
public class idcUSC_ID : colUSC_ID {}
public class idxIX_T_USER_COMM_USC_USER_ID
{
public const string _Name = "IX_T_USER_COMM_USC_USER_ID";
public const string _Caption = "IX_ T_ USER_ COMM_ USC_ USER_ ID";
public const string _ParentName = "T_USER_COMM";
public const bool _IsPrimaryKey = false;

public class ixcUSC_USER_ID : colUSC_USER_ID {}
}
public class idxPK_T_USER_COMM
{
public const string _Name = "PK_T_USER_COMM";
public const string _Caption = "PK_ T_ USER_ COMM";
public const string _ParentName = "T_USER_COMM";
public const bool _IsPrimaryKey = true;

public class ixcUSC_ID : colUSC_ID {}
}
public class pkxPK_T_USER_COMM : idxPK_T_USER_COMM {}
}
}
