//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.Tables
{
public class tblT_USER_LOGON
{
public const string _Name = "T_USER_LOGON";
public const string _Caption = "T_ USER_ LOGON";

public class colUSL_AGE
{
public const string _Name = "USL_AGE";
public const string _Caption = "USL_ AGE";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_AGE";
public const string _BindDataReader = "[USL_AGE]";
}
public class colUSL_CREDITS_BALANCE_UPDATED
{
public const string _Name = "USL_CREDITS_BALANCE_UPDATED";
public const string _Caption = "USL_ CREDITS_ BALANCE_ UPDATED";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_CREDITS_BALANCE_UPDATED";
public const string _BindDataReader = "[USL_CREDITS_BALANCE_UPDATED]";
}
public class colUSL_FB_UPDATED
{
public const string _Name = "USL_FB_UPDATED";
public const string _Caption = "USL_ FB_ UPDATED";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_FB_UPDATED";
public const string _BindDataReader = "[USL_FB_UPDATED]";
}
public class colUSL_FETCHED_LOCAL_ID
{
public const string _Name = "USL_FETCHED_LOCAL_ID";
public const string _Caption = "USL_ FETCHED_ LOCAL_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_FETCHED_LOCAL_ID";
public const string _BindDataReader = "[USL_FETCHED_LOCAL_ID]";
}
public class colUSL_FETCHED_LOGON_ID
{
public const string _Name = "USL_FETCHED_LOGON_ID";
public const string _Caption = "USL_ FETCHED_ LOGON_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_FETCHED_LOGON_ID";
public const string _BindDataReader = "[USL_FETCHED_LOGON_ID]";
}
public class colUSL_HAS_BREAKING_NEWS
{
public const string _Name = "USL_HAS_BREAKING_NEWS";
public const string _Caption = "USL_ HAS_ BREAKING_ NEWS";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_HAS_BREAKING_NEWS";
public const string _BindDataReader = "[USL_HAS_BREAKING_NEWS]";
}
public class colUSL_HAS_INBOX
{
public const string _Name = "USL_HAS_INBOX";
public const string _Caption = "USL_ HAS_ INBOX";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_HAS_INBOX";
public const string _BindDataReader = "[USL_HAS_INBOX]";
}
public class colUSL_HAS_ONLINE_FAVORITES
{
public const string _Name = "USL_HAS_ONLINE_FAVORITES";
public const string _Caption = "USL_ HAS_ ONLINE_ FAVORITES";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_HAS_ONLINE_FAVORITES";
public const string _BindDataReader = "[USL_HAS_ONLINE_FAVORITES]";
}
public class colUSL_ID
{
public const string _Name = "USL_ID";
public const string _Caption = "USL_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_ID";
public const string _BindDataReader = "[USL_ID]";
}
public class colUSL_IS_ONLINE
{
public const string _Name = "USL_IS_ONLINE";
public const string _Caption = "USL_ IS_ ONLINE";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_IS_ONLINE";
public const string _BindDataReader = "[USL_IS_ONLINE]";
}
public class colUSL_LINK_UPDATED
{
public const string _Name = "USL_LINK_UPDATED";
public const string _Caption = "USL_ LINK_ UPDATED";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_LINK_UPDATED";
public const string _BindDataReader = "[USL_LINK_UPDATED]";
}
public class colUSL_SID
{
public const string _Name = "USL_SID";
public const string _Caption = "USL_ SID";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_SID";
public const string _BindDataReader = "[USL_SID]";
}
public class colUSL_USER_ID
{
public const string _Name = "USL_USER_ID";
public const string _Caption = "USL_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_LOGON";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_LOGON.DefaultView.[0].USL_USER_ID";
public const string _BindDataReader = "[USL_USER_ID]";
}
public class idcUSL_ID : colUSL_ID {}
public class idxIX_T_USER_LOGON_USL_SID
{
public const string _Name = "IX_T_USER_LOGON_USL_SID";
public const string _Caption = "IX_ T_ USER_ LOGON_ USL_ SID";
public const string _ParentName = "T_USER_LOGON";
public const bool _IsPrimaryKey = false;

public class ixcUSL_SID : colUSL_SID {}
}
public class idxIX_T_USER_LOGON_USL_USER_ID
{
public const string _Name = "IX_T_USER_LOGON_USL_USER_ID";
public const string _Caption = "IX_ T_ USER_ LOGON_ USL_ USER_ ID";
public const string _ParentName = "T_USER_LOGON";
public const bool _IsPrimaryKey = false;

public class ixcUSL_USER_ID : colUSL_USER_ID {}
}
public class idxPK_T_USER_LOGON
{
public const string _Name = "PK_T_USER_LOGON";
public const string _Caption = "PK_ T_ USER_ LOGON";
public const string _ParentName = "T_USER_LOGON";
public const bool _IsPrimaryKey = true;

public class ixcUSL_ID : colUSL_ID {}
}
public class pkxPK_T_USER_LOGON : idxPK_T_USER_LOGON {}
}
}
