//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 07/12/2011 12:25
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.DBS.dbDatePercentDB.SPs
{
public class procAPT_USER_EMAILInsertInto
{
public const string _Name = "APT_USER_EMAILInsertInto";
public const string _Caption = "APT_ USER_ EMAILInsert Into";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_EMAILInsertInto";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
string p_strUSE_EMAIL, System.Nullable<int> p_iUSE_ID, System.Nullable<int> p_iUSE_USER_ID)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_EMAILInsertInto";
SqlParameterCollection(cmd.Parameters, p_strUSE_EMAIL, p_iUSE_ID, p_iUSE_USER_ID);
return cmd;
}
public static void SqlCommandOutput(
System.Data.SqlClient.SqlCommand p_cmd,
out object p_iUSE_ID)
{
p_iUSE_ID = p_cmd.Parameters["@USE_ID"].Value;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSE_EMAIL._SqlParameter());
p_oSqlParameterCollection.Add(parUSE_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSE_USER_ID._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, string p_strUSE_EMAIL, System.Nullable<int> p_iUSE_ID, System.Nullable<int> p_iUSE_USER_ID)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSE_EMAIL._SqlParameter(p_strUSE_EMAIL));
p_oSqlParameterCollection.Add(parUSE_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSE_USER_ID._SqlParameter(p_iUSE_USER_ID));
}
public class parUSE_EMAIL
{
public const string _Name = "@USE_EMAIL";
public const string _Caption = "@ USE_ EMAIL";
public const string _ParentName = "APT_USER_EMAILInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_EMAILInsertInto.DefaultView.[0].@USE_EMAIL";
public const string _BindDataReader = "[@USE_EMAIL]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USE_EMAIL", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USE_EMAIL", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSE_ID
{
public const string _Name = "@USE_ID";
public const string _Caption = "@ USE_ ID";
public const string _ParentName = "APT_USER_EMAILInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_EMAILInsertInto.DefaultView.[0].@USE_ID";
public const string _BindDataReader = "[@USE_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Output;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameter("@USE_ID", 10, 0, 4, SqlDbType.Int, ParameterDirection.Output, true);
}
}
public class parUSE_USER_ID
{
public const string _Name = "@USE_USER_ID";
public const string _Caption = "@ USE_ USER_ ID";
public const string _ParentName = "APT_USER_EMAILInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_EMAILInsertInto.DefaultView.[0].@USE_USER_ID";
public const string _BindDataReader = "[@USE_USER_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USE_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USE_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUSE_EMAIL : parUSE_EMAIL {}
public class inUSE_USER_ID : parUSE_USER_ID {}
public class outUSE_ID : parUSE_ID {}
public static int ExecuteNonQuery(
string p_strUSE_EMAIL, System.Nullable<int> p_iUSE_ID, System.Nullable<int> p_iUSE_USER_ID,out object p_iUSE_IDOut)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_strUSE_EMAIL, p_iUSE_ID, p_iUSE_USER_ID);
int iResult = db.ExecuteNonQuery(cmd);
SqlCommandOutput(cmd, out p_iUSE_IDOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
string p_strUSE_EMAIL, System.Nullable<int> p_iUSE_ID, System.Nullable<int> p_iUSE_USER_ID,out object p_iUSE_IDOut,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_strUSE_EMAIL, p_iUSE_ID, p_iUSE_USER_ID);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);
SqlCommandOutput(cmd, out p_iUSE_IDOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
