//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 07/12/2011 12:25
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.DBS.dbDatePercentDB.SPs
{
public class procAPT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE
{
public const string _Name = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const string _Caption = "APT_ LINK_ ACTION_ TYPE_ ENUMSelect By LAT_ CODE";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iLAT_CODE)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
SqlParameterCollection(cmd.Parameters, p_iLAT_CODE);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parLAT_CODE._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iLAT_CODE)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parLAT_CODE._SqlParameter(p_iLAT_CODE));
}
public class parLAT_CODE
{
public const string _Name = "@LAT_CODE";
public const string _Caption = "@ LAT_ CODE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE.DefaultView.[0].@LAT_CODE";
public const string _BindDataReader = "[@LAT_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@LAT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@LAT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class inLAT_CODE : parLAT_CODE {}
public class rsAPT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE
{
public const string _Name = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const string _Caption = "APT_ LINK_ ACTION_ TYPE_ ENUMSelect By LAT_ CODE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public class slcLAT_BUTTON_SIZE_CODE
{
public const string _Name = "LAT_BUTTON_SIZE_CODE";
public const string _Caption = "LAT_ BUTTON_ SIZE_ CODE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcLAT_CODE
{
public const string _Name = "LAT_CODE";
public const string _Caption = "LAT_ CODE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcLAT_DESCRIPTION
{
public const string _Name = "LAT_DESCRIPTION";
public const string _Caption = "LAT_ DESCRIPTION";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcLAT_EMAIL_BOX_TYPE
{
public const string _Name = "LAT_EMAIL_BOX_TYPE";
public const string _Caption = "LAT_ EMAIL_ BOX_ TYPE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcLAT_NAME
{
public const string _Name = "LAT_NAME";
public const string _Caption = "LAT_ NAME";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcLAT_RMN_TYPE
{
public const string _Name = "LAT_RMN_TYPE";
public const string _Caption = "LAT_ RMN_ TYPE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcLAT_SOURCE_LINK_TYPE
{
public const string _Name = "LAT_SOURCE_LINK_TYPE";
public const string _Caption = "LAT_ SOURCE_ LINK_ TYPE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcLAT_TARGET_LINK_TYPE
{
public const string _Name = "LAT_TARGET_LINK_TYPE";
public const string _Caption = "LAT_ TARGET_ LINK_ TYPE";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcLAT_TEXT
{
public const string _Name = "LAT_TEXT";
public const string _Caption = "LAT_ TEXT";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcValueCode
{
public const string _Name = "ValueCode";
public const string _Caption = "Value Code";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcValueName
{
public const string _Name = "ValueName";
public const string _Caption = "Value Name";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcValueNameEnum
{
public const string _Name = "ValueNameEnum";
public const string _Caption = "Value Name Enum";
public const string _ParentName = "APT_LINK_ACTION_TYPE_ENUMSelectByLAT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,System.Nullable<int> p_iLAT_CODE)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iLAT_CODE);
db.LoadDataSet(cmd, p_ds, p_strTableName);}
catch (System.Exception ex)
{
MADA.DatePercent.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,System.Nullable<int> p_iLAT_CODE,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iLAT_CODE);
p_db.LoadDataSet(cmd, p_ds, p_strTableName, p_trn);}
catch (System.Exception ex)
{
MADA.DatePercent.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
