//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 07/12/2011 12:25
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.DBS.dbDatePercentDB.SPs
{
public class procPT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE
{
public const string _Name = "PT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE";
public const string _Caption = "PT_ DOMAIN_ TYPE_ ENUMUpdate DMT_ FETCHERBy DMT_ CODE";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iDMT_CODE, string p_strDMT_FETCHER)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE";
SqlParameterCollection(cmd.Parameters, p_iDMT_CODE, p_strDMT_FETCHER);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parDMT_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parDMT_FETCHER._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iDMT_CODE, string p_strDMT_FETCHER)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parDMT_CODE._SqlParameter(p_iDMT_CODE));
p_oSqlParameterCollection.Add(parDMT_FETCHER._SqlParameter(p_strDMT_FETCHER));
}
public class parDMT_CODE
{
public const string _Name = "@DMT_CODE";
public const string _Caption = "@ DMT_ CODE";
public const string _ParentName = "PT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE.DefaultView.[0].@DMT_CODE";
public const string _BindDataReader = "[@DMT_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@DMT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@DMT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parDMT_FETCHER
{
public const string _Name = "@DMT_FETCHER";
public const string _Caption = "@ DMT_ FETCHER";
public const string _ParentName = "PT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_DOMAIN_TYPE_ENUMUpdateDMT_FETCHERByDMT_CODE.DefaultView.[0].@DMT_FETCHER";
public const string _BindDataReader = "[@DMT_FETCHER]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@DMT_FETCHER", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@DMT_FETCHER", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class inDMT_CODE : parDMT_CODE {}
public class inDMT_FETCHER : parDMT_FETCHER {}
public static int ExecuteNonQuery(
System.Nullable<int> p_iDMT_CODE, string p_strDMT_FETCHER)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iDMT_CODE, p_strDMT_FETCHER);
int iResult = db.ExecuteNonQuery(cmd);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
System.Nullable<int> p_iDMT_CODE, string p_strDMT_FETCHER,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iDMT_CODE, p_strDMT_FETCHER);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
