//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.SPs
{
public class procAPT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE
{
public const string _Name = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const string _Caption = "APT_ USER_ SETTINGInsert Into Update By USS_ USER_ IDUSS_ USER_ SETTING_ TYPE";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iiScopeIdentity, System.Nullable<bool> p_bUSS_BIT, System.Nullable<DateTime> p_dtUSS_DATETIME, System.Nullable<int> p_iUSS_ID, System.Nullable<int> p_iUSS_INT, string p_strUSS_NVARCHAR, System.Nullable<int> p_iUSS_USER_ID, System.Nullable<int> p_iUSS_USER_SETTING_TYPE)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
SqlParameterCollection(cmd.Parameters, p_iiScopeIdentity, p_bUSS_BIT, p_dtUSS_DATETIME, p_iUSS_ID, p_iUSS_INT, p_strUSS_NVARCHAR, p_iUSS_USER_ID, p_iUSS_USER_SETTING_TYPE);
return cmd;
}
public static void SqlCommandOutput(
System.Data.SqlClient.SqlCommand p_cmd,
out object p_iiScopeIdentity)
{
p_iiScopeIdentity = p_cmd.Parameters["@iScopeIdentity"].Value;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(pariScopeIdentity._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_BIT._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_DATETIME._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_INT._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_NVARCHAR._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_USER_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_USER_SETTING_TYPE._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iiScopeIdentity, System.Nullable<bool> p_bUSS_BIT, System.Nullable<DateTime> p_dtUSS_DATETIME, System.Nullable<int> p_iUSS_ID, System.Nullable<int> p_iUSS_INT, string p_strUSS_NVARCHAR, System.Nullable<int> p_iUSS_USER_ID, System.Nullable<int> p_iUSS_USER_SETTING_TYPE)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(pariScopeIdentity._SqlParameter());
p_oSqlParameterCollection.Add(parUSS_BIT._SqlParameter(p_bUSS_BIT));
p_oSqlParameterCollection.Add(parUSS_DATETIME._SqlParameter(p_dtUSS_DATETIME));
p_oSqlParameterCollection.Add(parUSS_ID._SqlParameter(p_iUSS_ID));
p_oSqlParameterCollection.Add(parUSS_INT._SqlParameter(p_iUSS_INT));
p_oSqlParameterCollection.Add(parUSS_NVARCHAR._SqlParameter(p_strUSS_NVARCHAR));
p_oSqlParameterCollection.Add(parUSS_USER_ID._SqlParameter(p_iUSS_USER_ID));
p_oSqlParameterCollection.Add(parUSS_USER_SETTING_TYPE._SqlParameter(p_iUSS_USER_SETTING_TYPE));
}
public class pariScopeIdentity
{
public const string _Name = "@iScopeIdentity";
public const string _Caption = "@i Scope Identity";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@iScopeIdentity";
public const string _BindDataReader = "[@iScopeIdentity]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Output;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameter("@iScopeIdentity", 10, 0, 4, SqlDbType.Int, ParameterDirection.Output, true);
}
}
public class parUSS_BIT
{
public const string _Name = "@USS_BIT";
public const string _Caption = "@ USS_ BIT";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@USS_BIT";
public const string _BindDataReader = "[@USS_BIT]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_BIT", 1, -1, 1, SqlDbType.Bit, "bool", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<bool> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_BIT", 1, -1, 1, SqlDbType.Bit, "bool", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSS_DATETIME
{
public const string _Name = "@USS_DATETIME";
public const string _Caption = "@ USS_ DATETIME";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.DateTime;
public const Int32 _Length = 8;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@USS_DATETIME";
public const string _BindDataReader = "[@USS_DATETIME]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_DATETIME", 23, 3, 8, SqlDbType.DateTime, "DateTime", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<DateTime> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_DATETIME", 23, 3, 8, SqlDbType.DateTime, "DateTime", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSS_ID
{
public const string _Name = "@USS_ID";
public const string _Caption = "@ USS_ ID";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@USS_ID";
public const string _BindDataReader = "[@USS_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSS_INT
{
public const string _Name = "@USS_INT";
public const string _Caption = "@ USS_ INT";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@USS_INT";
public const string _BindDataReader = "[@USS_INT]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_INT", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_INT", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSS_NVARCHAR
{
public const string _Name = "@USS_NVARCHAR";
public const string _Caption = "@ USS_ NVARCHAR";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@USS_NVARCHAR";
public const string _BindDataReader = "[@USS_NVARCHAR]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_NVARCHAR", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_NVARCHAR", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSS_USER_ID
{
public const string _Name = "@USS_USER_ID";
public const string _Caption = "@ USS_ USER_ ID";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@USS_USER_ID";
public const string _BindDataReader = "[@USS_USER_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSS_USER_SETTING_TYPE
{
public const string _Name = "@USS_USER_SETTING_TYPE";
public const string _Caption = "@ USS_ USER_ SETTING_ TYPE";
public const string _ParentName = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_SETTINGInsertIntoUpdateByUSS_USER_IDUSS_USER_SETTING_TYPE.DefaultView.[0].@USS_USER_SETTING_TYPE";
public const string _BindDataReader = "[@USS_USER_SETTING_TYPE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_USER_SETTING_TYPE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USS_USER_SETTING_TYPE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUSS_BIT : parUSS_BIT {}
public class inUSS_DATETIME : parUSS_DATETIME {}
public class inUSS_ID : parUSS_ID {}
public class inUSS_INT : parUSS_INT {}
public class inUSS_NVARCHAR : parUSS_NVARCHAR {}
public class inUSS_USER_ID : parUSS_USER_ID {}
public class inUSS_USER_SETTING_TYPE : parUSS_USER_SETTING_TYPE {}
public class outiScopeIdentity : pariScopeIdentity {}
public static int ExecuteNonQuery(
System.Nullable<int> p_iiScopeIdentity, System.Nullable<bool> p_bUSS_BIT, System.Nullable<DateTime> p_dtUSS_DATETIME, System.Nullable<int> p_iUSS_ID, System.Nullable<int> p_iUSS_INT, string p_strUSS_NVARCHAR, System.Nullable<int> p_iUSS_USER_ID, System.Nullable<int> p_iUSS_USER_SETTING_TYPE,out object p_iiScopeIdentityOut)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iiScopeIdentity, p_bUSS_BIT, p_dtUSS_DATETIME, p_iUSS_ID, p_iUSS_INT, p_strUSS_NVARCHAR, p_iUSS_USER_ID, p_iUSS_USER_SETTING_TYPE);
int iResult = db.ExecuteNonQuery(cmd);
SqlCommandOutput(cmd, out p_iiScopeIdentityOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
System.Nullable<int> p_iiScopeIdentity, System.Nullable<bool> p_bUSS_BIT, System.Nullable<DateTime> p_dtUSS_DATETIME, System.Nullable<int> p_iUSS_ID, System.Nullable<int> p_iUSS_INT, string p_strUSS_NVARCHAR, System.Nullable<int> p_iUSS_USER_ID, System.Nullable<int> p_iUSS_USER_SETTING_TYPE,out object p_iiScopeIdentityOut,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iiScopeIdentity, p_bUSS_BIT, p_dtUSS_DATETIME, p_iUSS_ID, p_iUSS_INT, p_strUSS_NVARCHAR, p_iUSS_USER_ID, p_iUSS_USER_SETTING_TYPE);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);
SqlCommandOutput(cmd, out p_iiScopeIdentityOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
