//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.SPs
{
public class procAPT_EMAIL_BOXInsertInto
{
public const string _Name = "APT_EMAIL_BOXInsertInto";
public const string _Caption = "APT_ EMAIL_ BOXInsert Into";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_EMAIL_BOXInsertInto";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
string p_strEMB_BOX_HTML, string p_strEMB_GETTER_EMAIL, string p_strEMB_GETTER_NAME, string p_strEMB_GETTER_USER_UID, System.Nullable<int> p_iEMB_ID, System.Nullable<DateTime> p_dtEMB_PUBLISH_DATETIME, string p_strEMB_SENDER_EMAIL, string p_strEMB_SENDER_NAME, string p_strEMB_SUBJECT)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_EMAIL_BOXInsertInto";
SqlParameterCollection(cmd.Parameters, p_strEMB_BOX_HTML, p_strEMB_GETTER_EMAIL, p_strEMB_GETTER_NAME, p_strEMB_GETTER_USER_UID, p_iEMB_ID, p_dtEMB_PUBLISH_DATETIME, p_strEMB_SENDER_EMAIL, p_strEMB_SENDER_NAME, p_strEMB_SUBJECT);
return cmd;
}
public static void SqlCommandOutput(
System.Data.SqlClient.SqlCommand p_cmd,
out object p_iEMB_ID)
{
p_iEMB_ID = p_cmd.Parameters["@EMB_ID"].Value;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parEMB_BOX_HTML._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_GETTER_EMAIL._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_GETTER_NAME._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_GETTER_USER_UID._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_ID._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_PUBLISH_DATETIME._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_SENDER_EMAIL._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_SENDER_NAME._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_SUBJECT._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, string p_strEMB_BOX_HTML, string p_strEMB_GETTER_EMAIL, string p_strEMB_GETTER_NAME, string p_strEMB_GETTER_USER_UID, System.Nullable<int> p_iEMB_ID, System.Nullable<DateTime> p_dtEMB_PUBLISH_DATETIME, string p_strEMB_SENDER_EMAIL, string p_strEMB_SENDER_NAME, string p_strEMB_SUBJECT)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parEMB_BOX_HTML._SqlParameter(p_strEMB_BOX_HTML));
p_oSqlParameterCollection.Add(parEMB_GETTER_EMAIL._SqlParameter(p_strEMB_GETTER_EMAIL));
p_oSqlParameterCollection.Add(parEMB_GETTER_NAME._SqlParameter(p_strEMB_GETTER_NAME));
p_oSqlParameterCollection.Add(parEMB_GETTER_USER_UID._SqlParameter(p_strEMB_GETTER_USER_UID));
p_oSqlParameterCollection.Add(parEMB_ID._SqlParameter());
p_oSqlParameterCollection.Add(parEMB_PUBLISH_DATETIME._SqlParameter(p_dtEMB_PUBLISH_DATETIME));
p_oSqlParameterCollection.Add(parEMB_SENDER_EMAIL._SqlParameter(p_strEMB_SENDER_EMAIL));
p_oSqlParameterCollection.Add(parEMB_SENDER_NAME._SqlParameter(p_strEMB_SENDER_NAME));
p_oSqlParameterCollection.Add(parEMB_SUBJECT._SqlParameter(p_strEMB_SUBJECT));
}
public class parEMB_BOX_HTML
{
public const string _Name = "@EMB_BOX_HTML";
public const string _Caption = "@ EMB_ BOX_ HTML";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 0;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_BOX_HTML";
public const string _BindDataReader = "[@EMB_BOX_HTML]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_BOX_HTML", -1, -1, 0, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_BOX_HTML", -1, -1, 0, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parEMB_GETTER_EMAIL
{
public const string _Name = "@EMB_GETTER_EMAIL";
public const string _Caption = "@ EMB_ GETTER_ EMAIL";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_GETTER_EMAIL";
public const string _BindDataReader = "[@EMB_GETTER_EMAIL]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_GETTER_EMAIL", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_GETTER_EMAIL", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parEMB_GETTER_NAME
{
public const string _Name = "@EMB_GETTER_NAME";
public const string _Caption = "@ EMB_ GETTER_ NAME";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_GETTER_NAME";
public const string _BindDataReader = "[@EMB_GETTER_NAME]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_GETTER_NAME", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_GETTER_NAME", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parEMB_GETTER_USER_UID
{
public const string _Name = "@EMB_GETTER_USER_UID";
public const string _Caption = "@ EMB_ GETTER_ USER_ UID";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_GETTER_USER_UID";
public const string _BindDataReader = "[@EMB_GETTER_USER_UID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_GETTER_USER_UID", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_GETTER_USER_UID", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parEMB_ID
{
public const string _Name = "@EMB_ID";
public const string _Caption = "@ EMB_ ID";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_ID";
public const string _BindDataReader = "[@EMB_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Output;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameter("@EMB_ID", 10, 0, 4, SqlDbType.Int, ParameterDirection.Output, true);
}
}
public class parEMB_PUBLISH_DATETIME
{
public const string _Name = "@EMB_PUBLISH_DATETIME";
public const string _Caption = "@ EMB_ PUBLISH_ DATETIME";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.DateTime;
public const Int32 _Length = 8;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_PUBLISH_DATETIME";
public const string _BindDataReader = "[@EMB_PUBLISH_DATETIME]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_PUBLISH_DATETIME", 23, 3, 8, SqlDbType.DateTime, "DateTime", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<DateTime> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_PUBLISH_DATETIME", 23, 3, 8, SqlDbType.DateTime, "DateTime", ParameterDirection.Input, true, false, "", Value);
}
}
public class parEMB_SENDER_EMAIL
{
public const string _Name = "@EMB_SENDER_EMAIL";
public const string _Caption = "@ EMB_ SENDER_ EMAIL";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_SENDER_EMAIL";
public const string _BindDataReader = "[@EMB_SENDER_EMAIL]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_SENDER_EMAIL", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_SENDER_EMAIL", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parEMB_SENDER_NAME
{
public const string _Name = "@EMB_SENDER_NAME";
public const string _Caption = "@ EMB_ SENDER_ NAME";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_SENDER_NAME";
public const string _BindDataReader = "[@EMB_SENDER_NAME]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_SENDER_NAME", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_SENDER_NAME", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parEMB_SUBJECT
{
public const string _Name = "@EMB_SUBJECT";
public const string _Caption = "@ EMB_ SUBJECT";
public const string _ParentName = "APT_EMAIL_BOXInsertInto";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_EMAIL_BOXInsertInto.DefaultView.[0].@EMB_SUBJECT";
public const string _BindDataReader = "[@EMB_SUBJECT]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_SUBJECT", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@EMB_SUBJECT", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class inEMB_BOX_HTML : parEMB_BOX_HTML {}
public class inEMB_GETTER_EMAIL : parEMB_GETTER_EMAIL {}
public class inEMB_GETTER_NAME : parEMB_GETTER_NAME {}
public class inEMB_GETTER_USER_UID : parEMB_GETTER_USER_UID {}
public class inEMB_PUBLISH_DATETIME : parEMB_PUBLISH_DATETIME {}
public class inEMB_SENDER_EMAIL : parEMB_SENDER_EMAIL {}
public class inEMB_SENDER_NAME : parEMB_SENDER_NAME {}
public class inEMB_SUBJECT : parEMB_SUBJECT {}
public class outEMB_ID : parEMB_ID {}
public static int ExecuteNonQuery(
string p_strEMB_BOX_HTML, string p_strEMB_GETTER_EMAIL, string p_strEMB_GETTER_NAME, string p_strEMB_GETTER_USER_UID, System.Nullable<int> p_iEMB_ID, System.Nullable<DateTime> p_dtEMB_PUBLISH_DATETIME, string p_strEMB_SENDER_EMAIL, string p_strEMB_SENDER_NAME, string p_strEMB_SUBJECT,out object p_iEMB_IDOut)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_strEMB_BOX_HTML, p_strEMB_GETTER_EMAIL, p_strEMB_GETTER_NAME, p_strEMB_GETTER_USER_UID, p_iEMB_ID, p_dtEMB_PUBLISH_DATETIME, p_strEMB_SENDER_EMAIL, p_strEMB_SENDER_NAME, p_strEMB_SUBJECT);
int iResult = db.ExecuteNonQuery(cmd);
SqlCommandOutput(cmd, out p_iEMB_IDOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
string p_strEMB_BOX_HTML, string p_strEMB_GETTER_EMAIL, string p_strEMB_GETTER_NAME, string p_strEMB_GETTER_USER_UID, System.Nullable<int> p_iEMB_ID, System.Nullable<DateTime> p_dtEMB_PUBLISH_DATETIME, string p_strEMB_SENDER_EMAIL, string p_strEMB_SENDER_NAME, string p_strEMB_SUBJECT,out object p_iEMB_IDOut,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_strEMB_BOX_HTML, p_strEMB_GETTER_EMAIL, p_strEMB_GETTER_NAME, p_strEMB_GETTER_USER_UID, p_iEMB_ID, p_dtEMB_PUBLISH_DATETIME, p_strEMB_SENDER_EMAIL, p_strEMB_SENDER_NAME, p_strEMB_SUBJECT);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);
SqlCommandOutput(cmd, out p_iEMB_IDOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
