//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.SPs
{
public class procAPT_USER_PROP_INTERESTSSelectByUIT_USER_ID
{
public const string _Name = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
public const string _Caption = "APT_ USER_ PROP_ INTERESTSSelect By UIT_ USER_ ID";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iUIT_USER_ID)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
SqlParameterCollection(cmd.Parameters, p_iUIT_USER_ID);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUIT_USER_ID._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iUIT_USER_ID)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUIT_USER_ID._SqlParameter(p_iUIT_USER_ID));
}
public class parUIT_USER_ID
{
public const string _Name = "@UIT_USER_ID";
public const string _Caption = "@ UIT_ USER_ ID";
public const string _ParentName = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID.DefaultView.[0].@UIT_USER_ID";
public const string _BindDataReader = "[@UIT_USER_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@UIT_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@UIT_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUIT_USER_ID : parUIT_USER_ID {}
public class rsAPT_USER_PROP_INTERESTSSelectByUIT_USER_ID
{
public const string _Name = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
public const string _Caption = "APT_ USER_ PROP_ INTERESTSSelect By UIT_ USER_ ID";
public const string _ParentName = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
public class slcUIT_ID
{
public const string _Name = "UIT_ID";
public const string _Caption = "UIT_ ID";
public const string _ParentName = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcUIT_PROP_INTERESTS_CODE
{
public const string _Name = "UIT_PROP_INTERESTS_CODE";
public const string _Caption = "UIT_ PROP_ INTERESTS_ CODE";
public const string _ParentName = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcUIT_USER_ID
{
public const string _Name = "UIT_USER_ID";
public const string _Caption = "UIT_ USER_ ID";
public const string _ParentName = "APT_USER_PROP_INTERESTSSelectByUIT_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,System.Nullable<int> p_iUIT_USER_ID)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iUIT_USER_ID);
db.LoadDataSet(cmd, p_ds, p_strTableName);}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,System.Nullable<int> p_iUIT_USER_ID,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iUIT_USER_ID);
p_db.LoadDataSet(cmd, p_ds, p_strTableName, p_trn);}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
