//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.SPs
{
public class procPT_USERUpdateProfileByUSR_ID
{
public const string _Name = "PT_USERUpdateProfileByUSR_ID";
public const string _Caption = "PT_ USERUpdate Profile By USR_ ID";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_USERUpdateProfileByUSR_ID";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iUSR_ID, string p_strUSR_NAME, string p_strUSR_PROP_ABOUT_ME, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_FROM_CODE, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_TO_CODE, System.Nullable<DateTime> p_dtUSR_PROP_BIRTHDATE, System.Nullable<int> p_iUSR_PROP_BODY_STYLE_CODE, System.Nullable<int> p_iUSR_PROP_CUSTODY_CODE, System.Nullable<int> p_iUSR_PROP_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_EDUCATION_CODE, System.Nullable<int> p_iUSR_PROP_EYE_CODE, System.Nullable<int> p_iUSR_PROP_HAIR_CODE, System.Nullable<int> p_iUSR_PROP_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_HEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SEX_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_WANT_KIDS_CODE, string p_strUSR_PROP_MY_IDEAL_MATCH, System.Nullable<int> p_iUSR_PROP_OCCUPATION_CODE, System.Nullable<int> p_iUSR_PROP_RACE_CODE, System.Nullable<int> p_iUSR_PROP_RELIGION_CODE, System.Nullable<int> p_iUSR_PROP_SEX_CODE, System.Nullable<int> p_iUSR_PROP_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_STATUS_CODE, System.Nullable<int> p_iUSR_PROP_WANT_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_WEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_ZODIAC_SIGN_CODE, System.Nullable<bool> p_bUSR_SUBSCRIBE, string p_strUSR_V_NAME)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_USERUpdateProfileByUSR_ID";
SqlParameterCollection(cmd.Parameters, p_iUSR_ID, p_strUSR_NAME, p_strUSR_PROP_ABOUT_ME, p_iUSR_PROP_AGE_RANGE_FROM_CODE, p_iUSR_PROP_AGE_RANGE_TO_CODE, p_dtUSR_PROP_BIRTHDATE, p_iUSR_PROP_BODY_STYLE_CODE, p_iUSR_PROP_CUSTODY_CODE, p_iUSR_PROP_DRINK_CODE, p_iUSR_PROP_EDUCATION_CODE, p_iUSR_PROP_EYE_CODE, p_iUSR_PROP_HAIR_CODE, p_iUSR_PROP_HAVE_KIDS_CODE, p_iUSR_PROP_HEIGHT_CODE, p_iUSR_PROP_MATCH_DRINK_CODE, p_iUSR_PROP_MATCH_HAVE_KIDS_CODE, p_iUSR_PROP_MATCH_SEX_CODE, p_iUSR_PROP_MATCH_SMOKE_CODE, p_iUSR_PROP_MATCH_WANT_KIDS_CODE, p_strUSR_PROP_MY_IDEAL_MATCH, p_iUSR_PROP_OCCUPATION_CODE, p_iUSR_PROP_RACE_CODE, p_iUSR_PROP_RELIGION_CODE, p_iUSR_PROP_SEX_CODE, p_iUSR_PROP_SMOKE_CODE, p_iUSR_PROP_STATUS_CODE, p_iUSR_PROP_WANT_KIDS_CODE, p_iUSR_PROP_WEIGHT_CODE, p_iUSR_PROP_ZODIAC_SIGN_CODE, p_bUSR_SUBSCRIBE, p_strUSR_V_NAME);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSR_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_NAME._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_ABOUT_ME._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_AGE_RANGE_FROM_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_AGE_RANGE_TO_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_BIRTHDATE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_BODY_STYLE_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_CUSTODY_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_DRINK_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_EDUCATION_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_EYE_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_HAIR_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_HAVE_KIDS_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_HEIGHT_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_DRINK_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_HAVE_KIDS_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_SEX_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_SMOKE_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_WANT_KIDS_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_MY_IDEAL_MATCH._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_OCCUPATION_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_RACE_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_RELIGION_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_SEX_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_SMOKE_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_STATUS_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_WANT_KIDS_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_WEIGHT_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_PROP_ZODIAC_SIGN_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_SUBSCRIBE._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_V_NAME._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iUSR_ID, string p_strUSR_NAME, string p_strUSR_PROP_ABOUT_ME, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_FROM_CODE, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_TO_CODE, System.Nullable<DateTime> p_dtUSR_PROP_BIRTHDATE, System.Nullable<int> p_iUSR_PROP_BODY_STYLE_CODE, System.Nullable<int> p_iUSR_PROP_CUSTODY_CODE, System.Nullable<int> p_iUSR_PROP_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_EDUCATION_CODE, System.Nullable<int> p_iUSR_PROP_EYE_CODE, System.Nullable<int> p_iUSR_PROP_HAIR_CODE, System.Nullable<int> p_iUSR_PROP_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_HEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SEX_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_WANT_KIDS_CODE, string p_strUSR_PROP_MY_IDEAL_MATCH, System.Nullable<int> p_iUSR_PROP_OCCUPATION_CODE, System.Nullable<int> p_iUSR_PROP_RACE_CODE, System.Nullable<int> p_iUSR_PROP_RELIGION_CODE, System.Nullable<int> p_iUSR_PROP_SEX_CODE, System.Nullable<int> p_iUSR_PROP_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_STATUS_CODE, System.Nullable<int> p_iUSR_PROP_WANT_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_WEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_ZODIAC_SIGN_CODE, System.Nullable<bool> p_bUSR_SUBSCRIBE, string p_strUSR_V_NAME)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSR_ID._SqlParameter(p_iUSR_ID));
p_oSqlParameterCollection.Add(parUSR_NAME._SqlParameter(p_strUSR_NAME));
p_oSqlParameterCollection.Add(parUSR_PROP_ABOUT_ME._SqlParameter(p_strUSR_PROP_ABOUT_ME));
p_oSqlParameterCollection.Add(parUSR_PROP_AGE_RANGE_FROM_CODE._SqlParameter(p_iUSR_PROP_AGE_RANGE_FROM_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_AGE_RANGE_TO_CODE._SqlParameter(p_iUSR_PROP_AGE_RANGE_TO_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_BIRTHDATE._SqlParameter(p_dtUSR_PROP_BIRTHDATE));
p_oSqlParameterCollection.Add(parUSR_PROP_BODY_STYLE_CODE._SqlParameter(p_iUSR_PROP_BODY_STYLE_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_CUSTODY_CODE._SqlParameter(p_iUSR_PROP_CUSTODY_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_DRINK_CODE._SqlParameter(p_iUSR_PROP_DRINK_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_EDUCATION_CODE._SqlParameter(p_iUSR_PROP_EDUCATION_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_EYE_CODE._SqlParameter(p_iUSR_PROP_EYE_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_HAIR_CODE._SqlParameter(p_iUSR_PROP_HAIR_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_HAVE_KIDS_CODE._SqlParameter(p_iUSR_PROP_HAVE_KIDS_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_HEIGHT_CODE._SqlParameter(p_iUSR_PROP_HEIGHT_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_DRINK_CODE._SqlParameter(p_iUSR_PROP_MATCH_DRINK_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_HAVE_KIDS_CODE._SqlParameter(p_iUSR_PROP_MATCH_HAVE_KIDS_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_SEX_CODE._SqlParameter(p_iUSR_PROP_MATCH_SEX_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_SMOKE_CODE._SqlParameter(p_iUSR_PROP_MATCH_SMOKE_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_MATCH_WANT_KIDS_CODE._SqlParameter(p_iUSR_PROP_MATCH_WANT_KIDS_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_MY_IDEAL_MATCH._SqlParameter(p_strUSR_PROP_MY_IDEAL_MATCH));
p_oSqlParameterCollection.Add(parUSR_PROP_OCCUPATION_CODE._SqlParameter(p_iUSR_PROP_OCCUPATION_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_RACE_CODE._SqlParameter(p_iUSR_PROP_RACE_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_RELIGION_CODE._SqlParameter(p_iUSR_PROP_RELIGION_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_SEX_CODE._SqlParameter(p_iUSR_PROP_SEX_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_SMOKE_CODE._SqlParameter(p_iUSR_PROP_SMOKE_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_STATUS_CODE._SqlParameter(p_iUSR_PROP_STATUS_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_WANT_KIDS_CODE._SqlParameter(p_iUSR_PROP_WANT_KIDS_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_WEIGHT_CODE._SqlParameter(p_iUSR_PROP_WEIGHT_CODE));
p_oSqlParameterCollection.Add(parUSR_PROP_ZODIAC_SIGN_CODE._SqlParameter(p_iUSR_PROP_ZODIAC_SIGN_CODE));
p_oSqlParameterCollection.Add(parUSR_SUBSCRIBE._SqlParameter(p_bUSR_SUBSCRIBE));
p_oSqlParameterCollection.Add(parUSR_V_NAME._SqlParameter(p_strUSR_V_NAME));
}
public class parUSR_ID
{
public const string _Name = "@USR_ID";
public const string _Caption = "@ USR_ ID";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_ID";
public const string _BindDataReader = "[@USR_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_NAME
{
public const string _Name = "@USR_NAME";
public const string _Caption = "@ USR_ NAME";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_NAME";
public const string _BindDataReader = "[@USR_NAME]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_NAME", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_NAME", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_ABOUT_ME
{
public const string _Name = "@USR_PROP_ABOUT_ME";
public const string _Caption = "@ USR_ PROP_ ABOUT_ ME";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_ABOUT_ME";
public const string _BindDataReader = "[@USR_PROP_ABOUT_ME]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_ABOUT_ME", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_ABOUT_ME", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_AGE_RANGE_FROM_CODE
{
public const string _Name = "@USR_PROP_AGE_RANGE_FROM_CODE";
public const string _Caption = "@ USR_ PROP_ AGE_ RANGE_ FROM_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_AGE_RANGE_FROM_CODE";
public const string _BindDataReader = "[@USR_PROP_AGE_RANGE_FROM_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_AGE_RANGE_FROM_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_AGE_RANGE_FROM_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_AGE_RANGE_TO_CODE
{
public const string _Name = "@USR_PROP_AGE_RANGE_TO_CODE";
public const string _Caption = "@ USR_ PROP_ AGE_ RANGE_ TO_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_AGE_RANGE_TO_CODE";
public const string _BindDataReader = "[@USR_PROP_AGE_RANGE_TO_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_AGE_RANGE_TO_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_AGE_RANGE_TO_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_BIRTHDATE
{
public const string _Name = "@USR_PROP_BIRTHDATE";
public const string _Caption = "@ USR_ PROP_ BIRTHDATE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.DateTime;
public const Int32 _Length = 8;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_BIRTHDATE";
public const string _BindDataReader = "[@USR_PROP_BIRTHDATE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_BIRTHDATE", 23, 3, 8, SqlDbType.DateTime, "DateTime", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<DateTime> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_BIRTHDATE", 23, 3, 8, SqlDbType.DateTime, "DateTime", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_BODY_STYLE_CODE
{
public const string _Name = "@USR_PROP_BODY_STYLE_CODE";
public const string _Caption = "@ USR_ PROP_ BODY_ STYLE_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_BODY_STYLE_CODE";
public const string _BindDataReader = "[@USR_PROP_BODY_STYLE_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_BODY_STYLE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_BODY_STYLE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_CUSTODY_CODE
{
public const string _Name = "@USR_PROP_CUSTODY_CODE";
public const string _Caption = "@ USR_ PROP_ CUSTODY_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_CUSTODY_CODE";
public const string _BindDataReader = "[@USR_PROP_CUSTODY_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_CUSTODY_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_CUSTODY_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_DRINK_CODE
{
public const string _Name = "@USR_PROP_DRINK_CODE";
public const string _Caption = "@ USR_ PROP_ DRINK_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_DRINK_CODE";
public const string _BindDataReader = "[@USR_PROP_DRINK_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_DRINK_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_DRINK_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_EDUCATION_CODE
{
public const string _Name = "@USR_PROP_EDUCATION_CODE";
public const string _Caption = "@ USR_ PROP_ EDUCATION_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_EDUCATION_CODE";
public const string _BindDataReader = "[@USR_PROP_EDUCATION_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_EDUCATION_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_EDUCATION_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_EYE_CODE
{
public const string _Name = "@USR_PROP_EYE_CODE";
public const string _Caption = "@ USR_ PROP_ EYE_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_EYE_CODE";
public const string _BindDataReader = "[@USR_PROP_EYE_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_EYE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_EYE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_HAIR_CODE
{
public const string _Name = "@USR_PROP_HAIR_CODE";
public const string _Caption = "@ USR_ PROP_ HAIR_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_HAIR_CODE";
public const string _BindDataReader = "[@USR_PROP_HAIR_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_HAIR_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_HAIR_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_HAVE_KIDS_CODE
{
public const string _Name = "@USR_PROP_HAVE_KIDS_CODE";
public const string _Caption = "@ USR_ PROP_ HAVE_ KIDS_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_HAVE_KIDS_CODE";
public const string _BindDataReader = "[@USR_PROP_HAVE_KIDS_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_HAVE_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_HAVE_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_HEIGHT_CODE
{
public const string _Name = "@USR_PROP_HEIGHT_CODE";
public const string _Caption = "@ USR_ PROP_ HEIGHT_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_HEIGHT_CODE";
public const string _BindDataReader = "[@USR_PROP_HEIGHT_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_HEIGHT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_HEIGHT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_MATCH_DRINK_CODE
{
public const string _Name = "@USR_PROP_MATCH_DRINK_CODE";
public const string _Caption = "@ USR_ PROP_ MATCH_ DRINK_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_MATCH_DRINK_CODE";
public const string _BindDataReader = "[@USR_PROP_MATCH_DRINK_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_DRINK_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_DRINK_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_MATCH_HAVE_KIDS_CODE
{
public const string _Name = "@USR_PROP_MATCH_HAVE_KIDS_CODE";
public const string _Caption = "@ USR_ PROP_ MATCH_ HAVE_ KIDS_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_MATCH_HAVE_KIDS_CODE";
public const string _BindDataReader = "[@USR_PROP_MATCH_HAVE_KIDS_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_HAVE_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_HAVE_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_MATCH_SEX_CODE
{
public const string _Name = "@USR_PROP_MATCH_SEX_CODE";
public const string _Caption = "@ USR_ PROP_ MATCH_ SEX_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_MATCH_SEX_CODE";
public const string _BindDataReader = "[@USR_PROP_MATCH_SEX_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_SEX_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_SEX_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_MATCH_SMOKE_CODE
{
public const string _Name = "@USR_PROP_MATCH_SMOKE_CODE";
public const string _Caption = "@ USR_ PROP_ MATCH_ SMOKE_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_MATCH_SMOKE_CODE";
public const string _BindDataReader = "[@USR_PROP_MATCH_SMOKE_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_SMOKE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_SMOKE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_MATCH_WANT_KIDS_CODE
{
public const string _Name = "@USR_PROP_MATCH_WANT_KIDS_CODE";
public const string _Caption = "@ USR_ PROP_ MATCH_ WANT_ KIDS_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_MATCH_WANT_KIDS_CODE";
public const string _BindDataReader = "[@USR_PROP_MATCH_WANT_KIDS_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_WANT_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MATCH_WANT_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_MY_IDEAL_MATCH
{
public const string _Name = "@USR_PROP_MY_IDEAL_MATCH";
public const string _Caption = "@ USR_ PROP_ MY_ IDEAL_ MATCH";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_MY_IDEAL_MATCH";
public const string _BindDataReader = "[@USR_PROP_MY_IDEAL_MATCH]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MY_IDEAL_MATCH", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_MY_IDEAL_MATCH", 2000, -1, 2000, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_OCCUPATION_CODE
{
public const string _Name = "@USR_PROP_OCCUPATION_CODE";
public const string _Caption = "@ USR_ PROP_ OCCUPATION_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_OCCUPATION_CODE";
public const string _BindDataReader = "[@USR_PROP_OCCUPATION_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_OCCUPATION_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_OCCUPATION_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_RACE_CODE
{
public const string _Name = "@USR_PROP_RACE_CODE";
public const string _Caption = "@ USR_ PROP_ RACE_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_RACE_CODE";
public const string _BindDataReader = "[@USR_PROP_RACE_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_RACE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_RACE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_RELIGION_CODE
{
public const string _Name = "@USR_PROP_RELIGION_CODE";
public const string _Caption = "@ USR_ PROP_ RELIGION_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_RELIGION_CODE";
public const string _BindDataReader = "[@USR_PROP_RELIGION_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_RELIGION_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_RELIGION_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_SEX_CODE
{
public const string _Name = "@USR_PROP_SEX_CODE";
public const string _Caption = "@ USR_ PROP_ SEX_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_SEX_CODE";
public const string _BindDataReader = "[@USR_PROP_SEX_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_SEX_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_SEX_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_SMOKE_CODE
{
public const string _Name = "@USR_PROP_SMOKE_CODE";
public const string _Caption = "@ USR_ PROP_ SMOKE_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_SMOKE_CODE";
public const string _BindDataReader = "[@USR_PROP_SMOKE_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_SMOKE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_SMOKE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_STATUS_CODE
{
public const string _Name = "@USR_PROP_STATUS_CODE";
public const string _Caption = "@ USR_ PROP_ STATUS_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_STATUS_CODE";
public const string _BindDataReader = "[@USR_PROP_STATUS_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_STATUS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_STATUS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_WANT_KIDS_CODE
{
public const string _Name = "@USR_PROP_WANT_KIDS_CODE";
public const string _Caption = "@ USR_ PROP_ WANT_ KIDS_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_WANT_KIDS_CODE";
public const string _BindDataReader = "[@USR_PROP_WANT_KIDS_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_WANT_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_WANT_KIDS_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_WEIGHT_CODE
{
public const string _Name = "@USR_PROP_WEIGHT_CODE";
public const string _Caption = "@ USR_ PROP_ WEIGHT_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_WEIGHT_CODE";
public const string _BindDataReader = "[@USR_PROP_WEIGHT_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_WEIGHT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_WEIGHT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_PROP_ZODIAC_SIGN_CODE
{
public const string _Name = "@USR_PROP_ZODIAC_SIGN_CODE";
public const string _Caption = "@ USR_ PROP_ ZODIAC_ SIGN_ CODE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_PROP_ZODIAC_SIGN_CODE";
public const string _BindDataReader = "[@USR_PROP_ZODIAC_SIGN_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_ZODIAC_SIGN_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_PROP_ZODIAC_SIGN_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_SUBSCRIBE
{
public const string _Name = "@USR_SUBSCRIBE";
public const string _Caption = "@ USR_ SUBSCRIBE";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_SUBSCRIBE";
public const string _BindDataReader = "[@USR_SUBSCRIBE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_SUBSCRIBE", 1, -1, 1, SqlDbType.Bit, "bool", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<bool> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_SUBSCRIBE", 1, -1, 1, SqlDbType.Bit, "bool", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_V_NAME
{
public const string _Name = "@USR_V_NAME";
public const string _Caption = "@ USR_ V_ NAME";
public const string _ParentName = "PT_USERUpdateProfileByUSR_ID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 10;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateProfileByUSR_ID.DefaultView.[0].@USR_V_NAME";
public const string _BindDataReader = "[@USR_V_NAME]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_V_NAME", 10, -1, 10, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_V_NAME", 10, -1, 10, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUSR_ID : parUSR_ID {}
public class inUSR_NAME : parUSR_NAME {}
public class inUSR_PROP_ABOUT_ME : parUSR_PROP_ABOUT_ME {}
public class inUSR_PROP_AGE_RANGE_FROM_CODE : parUSR_PROP_AGE_RANGE_FROM_CODE {}
public class inUSR_PROP_AGE_RANGE_TO_CODE : parUSR_PROP_AGE_RANGE_TO_CODE {}
public class inUSR_PROP_BIRTHDATE : parUSR_PROP_BIRTHDATE {}
public class inUSR_PROP_BODY_STYLE_CODE : parUSR_PROP_BODY_STYLE_CODE {}
public class inUSR_PROP_CUSTODY_CODE : parUSR_PROP_CUSTODY_CODE {}
public class inUSR_PROP_DRINK_CODE : parUSR_PROP_DRINK_CODE {}
public class inUSR_PROP_EDUCATION_CODE : parUSR_PROP_EDUCATION_CODE {}
public class inUSR_PROP_EYE_CODE : parUSR_PROP_EYE_CODE {}
public class inUSR_PROP_HAIR_CODE : parUSR_PROP_HAIR_CODE {}
public class inUSR_PROP_HAVE_KIDS_CODE : parUSR_PROP_HAVE_KIDS_CODE {}
public class inUSR_PROP_HEIGHT_CODE : parUSR_PROP_HEIGHT_CODE {}
public class inUSR_PROP_MATCH_DRINK_CODE : parUSR_PROP_MATCH_DRINK_CODE {}
public class inUSR_PROP_MATCH_HAVE_KIDS_CODE : parUSR_PROP_MATCH_HAVE_KIDS_CODE {}
public class inUSR_PROP_MATCH_SEX_CODE : parUSR_PROP_MATCH_SEX_CODE {}
public class inUSR_PROP_MATCH_SMOKE_CODE : parUSR_PROP_MATCH_SMOKE_CODE {}
public class inUSR_PROP_MATCH_WANT_KIDS_CODE : parUSR_PROP_MATCH_WANT_KIDS_CODE {}
public class inUSR_PROP_MY_IDEAL_MATCH : parUSR_PROP_MY_IDEAL_MATCH {}
public class inUSR_PROP_OCCUPATION_CODE : parUSR_PROP_OCCUPATION_CODE {}
public class inUSR_PROP_RACE_CODE : parUSR_PROP_RACE_CODE {}
public class inUSR_PROP_RELIGION_CODE : parUSR_PROP_RELIGION_CODE {}
public class inUSR_PROP_SEX_CODE : parUSR_PROP_SEX_CODE {}
public class inUSR_PROP_SMOKE_CODE : parUSR_PROP_SMOKE_CODE {}
public class inUSR_PROP_STATUS_CODE : parUSR_PROP_STATUS_CODE {}
public class inUSR_PROP_WANT_KIDS_CODE : parUSR_PROP_WANT_KIDS_CODE {}
public class inUSR_PROP_WEIGHT_CODE : parUSR_PROP_WEIGHT_CODE {}
public class inUSR_PROP_ZODIAC_SIGN_CODE : parUSR_PROP_ZODIAC_SIGN_CODE {}
public class inUSR_SUBSCRIBE : parUSR_SUBSCRIBE {}
public class inUSR_V_NAME : parUSR_V_NAME {}
public static int ExecuteNonQuery(
System.Nullable<int> p_iUSR_ID, string p_strUSR_NAME, string p_strUSR_PROP_ABOUT_ME, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_FROM_CODE, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_TO_CODE, System.Nullable<DateTime> p_dtUSR_PROP_BIRTHDATE, System.Nullable<int> p_iUSR_PROP_BODY_STYLE_CODE, System.Nullable<int> p_iUSR_PROP_CUSTODY_CODE, System.Nullable<int> p_iUSR_PROP_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_EDUCATION_CODE, System.Nullable<int> p_iUSR_PROP_EYE_CODE, System.Nullable<int> p_iUSR_PROP_HAIR_CODE, System.Nullable<int> p_iUSR_PROP_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_HEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SEX_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_WANT_KIDS_CODE, string p_strUSR_PROP_MY_IDEAL_MATCH, System.Nullable<int> p_iUSR_PROP_OCCUPATION_CODE, System.Nullable<int> p_iUSR_PROP_RACE_CODE, System.Nullable<int> p_iUSR_PROP_RELIGION_CODE, System.Nullable<int> p_iUSR_PROP_SEX_CODE, System.Nullable<int> p_iUSR_PROP_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_STATUS_CODE, System.Nullable<int> p_iUSR_PROP_WANT_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_WEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_ZODIAC_SIGN_CODE, System.Nullable<bool> p_bUSR_SUBSCRIBE, string p_strUSR_V_NAME)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iUSR_ID, p_strUSR_NAME, p_strUSR_PROP_ABOUT_ME, p_iUSR_PROP_AGE_RANGE_FROM_CODE, p_iUSR_PROP_AGE_RANGE_TO_CODE, p_dtUSR_PROP_BIRTHDATE, p_iUSR_PROP_BODY_STYLE_CODE, p_iUSR_PROP_CUSTODY_CODE, p_iUSR_PROP_DRINK_CODE, p_iUSR_PROP_EDUCATION_CODE, p_iUSR_PROP_EYE_CODE, p_iUSR_PROP_HAIR_CODE, p_iUSR_PROP_HAVE_KIDS_CODE, p_iUSR_PROP_HEIGHT_CODE, p_iUSR_PROP_MATCH_DRINK_CODE, p_iUSR_PROP_MATCH_HAVE_KIDS_CODE, p_iUSR_PROP_MATCH_SEX_CODE, p_iUSR_PROP_MATCH_SMOKE_CODE, p_iUSR_PROP_MATCH_WANT_KIDS_CODE, p_strUSR_PROP_MY_IDEAL_MATCH, p_iUSR_PROP_OCCUPATION_CODE, p_iUSR_PROP_RACE_CODE, p_iUSR_PROP_RELIGION_CODE, p_iUSR_PROP_SEX_CODE, p_iUSR_PROP_SMOKE_CODE, p_iUSR_PROP_STATUS_CODE, p_iUSR_PROP_WANT_KIDS_CODE, p_iUSR_PROP_WEIGHT_CODE, p_iUSR_PROP_ZODIAC_SIGN_CODE, p_bUSR_SUBSCRIBE, p_strUSR_V_NAME);
int iResult = db.ExecuteNonQuery(cmd);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
System.Nullable<int> p_iUSR_ID, string p_strUSR_NAME, string p_strUSR_PROP_ABOUT_ME, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_FROM_CODE, System.Nullable<int> p_iUSR_PROP_AGE_RANGE_TO_CODE, System.Nullable<DateTime> p_dtUSR_PROP_BIRTHDATE, System.Nullable<int> p_iUSR_PROP_BODY_STYLE_CODE, System.Nullable<int> p_iUSR_PROP_CUSTODY_CODE, System.Nullable<int> p_iUSR_PROP_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_EDUCATION_CODE, System.Nullable<int> p_iUSR_PROP_EYE_CODE, System.Nullable<int> p_iUSR_PROP_HAIR_CODE, System.Nullable<int> p_iUSR_PROP_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_HEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_DRINK_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_HAVE_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SEX_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_MATCH_WANT_KIDS_CODE, string p_strUSR_PROP_MY_IDEAL_MATCH, System.Nullable<int> p_iUSR_PROP_OCCUPATION_CODE, System.Nullable<int> p_iUSR_PROP_RACE_CODE, System.Nullable<int> p_iUSR_PROP_RELIGION_CODE, System.Nullable<int> p_iUSR_PROP_SEX_CODE, System.Nullable<int> p_iUSR_PROP_SMOKE_CODE, System.Nullable<int> p_iUSR_PROP_STATUS_CODE, System.Nullable<int> p_iUSR_PROP_WANT_KIDS_CODE, System.Nullable<int> p_iUSR_PROP_WEIGHT_CODE, System.Nullable<int> p_iUSR_PROP_ZODIAC_SIGN_CODE, System.Nullable<bool> p_bUSR_SUBSCRIBE, string p_strUSR_V_NAME,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iUSR_ID, p_strUSR_NAME, p_strUSR_PROP_ABOUT_ME, p_iUSR_PROP_AGE_RANGE_FROM_CODE, p_iUSR_PROP_AGE_RANGE_TO_CODE, p_dtUSR_PROP_BIRTHDATE, p_iUSR_PROP_BODY_STYLE_CODE, p_iUSR_PROP_CUSTODY_CODE, p_iUSR_PROP_DRINK_CODE, p_iUSR_PROP_EDUCATION_CODE, p_iUSR_PROP_EYE_CODE, p_iUSR_PROP_HAIR_CODE, p_iUSR_PROP_HAVE_KIDS_CODE, p_iUSR_PROP_HEIGHT_CODE, p_iUSR_PROP_MATCH_DRINK_CODE, p_iUSR_PROP_MATCH_HAVE_KIDS_CODE, p_iUSR_PROP_MATCH_SEX_CODE, p_iUSR_PROP_MATCH_SMOKE_CODE, p_iUSR_PROP_MATCH_WANT_KIDS_CODE, p_strUSR_PROP_MY_IDEAL_MATCH, p_iUSR_PROP_OCCUPATION_CODE, p_iUSR_PROP_RACE_CODE, p_iUSR_PROP_RELIGION_CODE, p_iUSR_PROP_SEX_CODE, p_iUSR_PROP_SMOKE_CODE, p_iUSR_PROP_STATUS_CODE, p_iUSR_PROP_WANT_KIDS_CODE, p_iUSR_PROP_WEIGHT_CODE, p_iUSR_PROP_ZODIAC_SIGN_CODE, p_bUSR_SUBSCRIBE, p_strUSR_V_NAME);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.WL.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
