//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 07/12/2011 12:25
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.DBS.dbDatePercentDB.Tables
{
public class tblT_EMAIL
{
public const string _Name = "T_EMAIL";
public const string _Caption = "T_ EMAIL";

public class colEML_BODY
{
public const string _Name = "EML_BODY";
public const string _Caption = "EML_ BODY";
public const string _Description = "";
public const string _ParentName = "T_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 0;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_EMAIL.DefaultView.[0].EML_BODY";
public const string _BindDataReader = "[EML_BODY]";
}
public class colEML_GETTER_EMAIL
{
public const string _Name = "EML_GETTER_EMAIL";
public const string _Caption = "EML_ GETTER_ EMAIL";
public const string _Description = "";
public const string _ParentName = "T_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_EMAIL.DefaultView.[0].EML_GETTER_EMAIL";
public const string _BindDataReader = "[EML_GETTER_EMAIL]";
}
public class colEML_GETTER_NAME
{
public const string _Name = "EML_GETTER_NAME";
public const string _Caption = "EML_ GETTER_ NAME";
public const string _Description = "";
public const string _ParentName = "T_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_EMAIL.DefaultView.[0].EML_GETTER_NAME";
public const string _BindDataReader = "[EML_GETTER_NAME]";
}
public class colEML_ID
{
public const string _Name = "EML_ID";
public const string _Caption = "EML_ ID";
public const string _Description = "";
public const string _ParentName = "T_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_EMAIL.DefaultView.[0].EML_ID";
public const string _BindDataReader = "[EML_ID]";
}
public class colEML_SENDER_NAME
{
public const string _Name = "EML_SENDER_NAME";
public const string _Caption = "EML_ SENDER_ NAME";
public const string _Description = "";
public const string _ParentName = "T_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_EMAIL.DefaultView.[0].EML_SENDER_NAME";
public const string _BindDataReader = "[EML_SENDER_NAME]";
}
public class colEML_SUBJECT
{
public const string _Name = "EML_SUBJECT";
public const string _Caption = "EML_ SUBJECT";
public const string _Description = "";
public const string _ParentName = "T_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_EMAIL.DefaultView.[0].EML_SUBJECT";
public const string _BindDataReader = "[EML_SUBJECT]";
}
public class idcEML_ID : colEML_ID {}
public class idxPK_T_EMAIL
{
public const string _Name = "PK_T_EMAIL";
public const string _Caption = "PK_ T_ EMAIL";
public const string _ParentName = "T_EMAIL";
public const bool _IsPrimaryKey = true;

public class ixcEML_ID : colEML_ID {}
}
public class pkxPK_T_EMAIL : idxPK_T_EMAIL {}
}
}
