//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 07/12/2011 12:25
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.DBS.dbDatePercentDB.Tables
{
public class tblT_PROP_INTERESTS_TYPE
{
public const string _Name = "T_PROP_INTERESTS_TYPE";
public const string _Caption = "T_ PROP_ INTERESTS_ TYPE";

public class colINT_CODE
{
public const string _Name = "INT_CODE";
public const string _Caption = "INT_ CODE";
public const string _Description = "";
public const string _ParentName = "T_PROP_INTERESTS_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_PROP_INTERESTS_TYPE.DefaultView.[0].INT_CODE";
public const string _BindDataReader = "[INT_CODE]";
}
public class colINT_DESCRIPTION
{
public const string _Name = "INT_DESCRIPTION";
public const string _Caption = "INT_ DESCRIPTION";
public const string _Description = "";
public const string _ParentName = "T_PROP_INTERESTS_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_PROP_INTERESTS_TYPE.DefaultView.[0].INT_DESCRIPTION";
public const string _BindDataReader = "[INT_DESCRIPTION]";
}
public class idxPK_T_PROP_INTERESTS_TYPE
{
public const string _Name = "PK_T_PROP_INTERESTS_TYPE";
public const string _Caption = "PK_ T_ PROP_ INTERESTS_ TYPE";
public const string _ParentName = "T_PROP_INTERESTS_TYPE";
public const bool _IsPrimaryKey = true;

public class ixcINT_CODE : colINT_CODE {}
}
public class pkxPK_T_PROP_INTERESTS_TYPE : idxPK_T_PROP_INTERESTS_TYPE {}
}
}
