//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 07/12/2011 12:25
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.DBS.dbDatePercentDB.Tables
{
public class tblT_USER_EMAIL
{
public const string _Name = "T_USER_EMAIL";
public const string _Caption = "T_ USER_ EMAIL";

public class colUSE_EMAIL
{
public const string _Name = "USE_EMAIL";
public const string _Caption = "USE_ EMAIL";
public const string _Description = "";
public const string _ParentName = "T_USER_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_EMAIL.DefaultView.[0].USE_EMAIL";
public const string _BindDataReader = "[USE_EMAIL]";
}
public class colUSE_ID
{
public const string _Name = "USE_ID";
public const string _Caption = "USE_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_USER_EMAIL.DefaultView.[0].USE_ID";
public const string _BindDataReader = "[USE_ID]";
}
public class colUSE_USER_ID
{
public const string _Name = "USE_USER_ID";
public const string _Caption = "USE_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_EMAIL";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_EMAIL.DefaultView.[0].USE_USER_ID";
public const string _BindDataReader = "[USE_USER_ID]";
}
public class idcUSE_ID : colUSE_ID {}
public class idxIX_T_USER_EMAIL_USE_EMAIL
{
public const string _Name = "IX_T_USER_EMAIL_USE_EMAIL";
public const string _Caption = "IX_ T_ USER_ EMAIL_ USE_ EMAIL";
public const string _ParentName = "T_USER_EMAIL";
public const bool _IsPrimaryKey = false;

public class ixcUSE_EMAIL : colUSE_EMAIL {}
}
public class idxIX_T_USER_EMAIL_USE_USER_ID
{
public const string _Name = "IX_T_USER_EMAIL_USE_USER_ID";
public const string _Caption = "IX_ T_ USER_ EMAIL_ USE_ USER_ ID";
public const string _ParentName = "T_USER_EMAIL";
public const bool _IsPrimaryKey = false;

public class ixcUSE_USER_ID : colUSE_USER_ID {}
}
public class idxIX_T_USER_EMAIL_USE_USER_ID_USE_EMAIL
{
public const string _Name = "IX_T_USER_EMAIL_USE_USER_ID_USE_EMAIL";
public const string _Caption = "IX_ T_ USER_ EMAIL_ USE_ USER_ ID_ USE_ EMAIL";
public const string _ParentName = "T_USER_EMAIL";
public const bool _IsPrimaryKey = false;

public class ixcUSE_EMAIL : colUSE_EMAIL {}
public class ixcUSE_USER_ID : colUSE_USER_ID {}
}
public class idxPK_T_USER_EMAIL
{
public const string _Name = "PK_T_USER_EMAIL";
public const string _Caption = "PK_ T_ USER_ EMAIL";
public const string _ParentName = "T_USER_EMAIL";
public const bool _IsPrimaryKey = true;

public class ixcUSE_ID : colUSE_ID {}
}
public class pkxPK_T_USER_EMAIL : idxPK_T_USER_EMAIL {}
}
}
