//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.SPs
{
public class procAPT_USER_LOGONInsertIntoUpdateByUSL_SID
{
public const string _Name = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
public const string _Caption = "APT_ USER_ LOGONInsert Into Update By USL_ SID";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iiScopeIdentity, System.Nullable<int> p_iUSL_AGE, System.Nullable<int> p_iUSL_ID, string p_strUSL_SID, System.Nullable<int> p_iUSL_USER_ID)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
SqlParameterCollection(cmd.Parameters, p_iiScopeIdentity, p_iUSL_AGE, p_iUSL_ID, p_strUSL_SID, p_iUSL_USER_ID);
return cmd;
}
public static void SqlCommandOutput(
System.Data.SqlClient.SqlCommand p_cmd,
out object p_iiScopeIdentity)
{
p_iiScopeIdentity = p_cmd.Parameters["@iScopeIdentity"].Value;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(pariScopeIdentity._SqlParameter());
p_oSqlParameterCollection.Add(parUSL_AGE._SqlParameter());
p_oSqlParameterCollection.Add(parUSL_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSL_SID._SqlParameter());
p_oSqlParameterCollection.Add(parUSL_USER_ID._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iiScopeIdentity, System.Nullable<int> p_iUSL_AGE, System.Nullable<int> p_iUSL_ID, string p_strUSL_SID, System.Nullable<int> p_iUSL_USER_ID)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(pariScopeIdentity._SqlParameter());
p_oSqlParameterCollection.Add(parUSL_AGE._SqlParameter(p_iUSL_AGE));
p_oSqlParameterCollection.Add(parUSL_ID._SqlParameter(p_iUSL_ID));
p_oSqlParameterCollection.Add(parUSL_SID._SqlParameter(p_strUSL_SID));
p_oSqlParameterCollection.Add(parUSL_USER_ID._SqlParameter(p_iUSL_USER_ID));
}
public class pariScopeIdentity
{
public const string _Name = "@iScopeIdentity";
public const string _Caption = "@i Scope Identity";
public const string _ParentName = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_LOGONInsertIntoUpdateByUSL_SID.DefaultView.[0].@iScopeIdentity";
public const string _BindDataReader = "[@iScopeIdentity]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Output;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameter("@iScopeIdentity", 10, 0, 4, SqlDbType.Int, ParameterDirection.Output, true);
}
}
public class parUSL_AGE
{
public const string _Name = "@USL_AGE";
public const string _Caption = "@ USL_ AGE";
public const string _ParentName = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_LOGONInsertIntoUpdateByUSL_SID.DefaultView.[0].@USL_AGE";
public const string _BindDataReader = "[@USL_AGE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_AGE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_AGE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSL_ID
{
public const string _Name = "@USL_ID";
public const string _Caption = "@ USL_ ID";
public const string _ParentName = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_LOGONInsertIntoUpdateByUSL_SID.DefaultView.[0].@USL_ID";
public const string _BindDataReader = "[@USL_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSL_SID
{
public const string _Name = "@USL_SID";
public const string _Caption = "@ USL_ SID";
public const string _ParentName = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_LOGONInsertIntoUpdateByUSL_SID.DefaultView.[0].@USL_SID";
public const string _BindDataReader = "[@USL_SID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_SID", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_SID", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSL_USER_ID
{
public const string _Name = "@USL_USER_ID";
public const string _Caption = "@ USL_ USER_ ID";
public const string _ParentName = "APT_USER_LOGONInsertIntoUpdateByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_LOGONInsertIntoUpdateByUSL_SID.DefaultView.[0].@USL_USER_ID";
public const string _BindDataReader = "[@USL_USER_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUSL_AGE : parUSL_AGE {}
public class inUSL_ID : parUSL_ID {}
public class inUSL_SID : parUSL_SID {}
public class inUSL_USER_ID : parUSL_USER_ID {}
public class outiScopeIdentity : pariScopeIdentity {}
public static int ExecuteNonQuery(
System.Nullable<int> p_iiScopeIdentity, System.Nullable<int> p_iUSL_AGE, System.Nullable<int> p_iUSL_ID, string p_strUSL_SID, System.Nullable<int> p_iUSL_USER_ID,out object p_iiScopeIdentityOut)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iiScopeIdentity, p_iUSL_AGE, p_iUSL_ID, p_strUSL_SID, p_iUSL_USER_ID);
int iResult = db.ExecuteNonQuery(cmd);
SqlCommandOutput(cmd, out p_iiScopeIdentityOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
System.Nullable<int> p_iiScopeIdentity, System.Nullable<int> p_iUSL_AGE, System.Nullable<int> p_iUSL_ID, string p_strUSL_SID, System.Nullable<int> p_iUSL_USER_ID,out object p_iiScopeIdentityOut,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iiScopeIdentity, p_iUSL_AGE, p_iUSL_ID, p_strUSL_SID, p_iUSL_USER_ID);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);
SqlCommandOutput(cmd, out p_iiScopeIdentityOut);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
