//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.SPs
{
public class procAPT_USER_LOGONSelectByUSL_SID
{
public const string _Name = "APT_USER_LOGONSelectByUSL_SID";
public const string _Caption = "APT_ USER_ LOGONSelect By USL_ SID";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_LOGONSelectByUSL_SID";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
string p_strUSL_SID)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_USER_LOGONSelectByUSL_SID";
SqlParameterCollection(cmd.Parameters, p_strUSL_SID);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSL_SID._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, string p_strUSL_SID)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSL_SID._SqlParameter(p_strUSL_SID));
}
public class parUSL_SID
{
public const string _Name = "@USL_SID";
public const string _Caption = "@ USL_ SID";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_USER_LOGONSelectByUSL_SID.DefaultView.[0].@USL_SID";
public const string _BindDataReader = "[@USL_SID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_SID", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_SID", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUSL_SID : parUSL_SID {}
public class rsAPT_USER_LOGONSelectByUSL_SID
{
public const string _Name = "APT_USER_LOGONSelectByUSL_SID";
public const string _Caption = "APT_ USER_ LOGONSelect By USL_ SID";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public class slcUSL_AGE
{
public const string _Name = "USL_AGE";
public const string _Caption = "USL_ AGE";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcUSL_CREDITS_BALANCE_UPDATED
{
public const string _Name = "USL_CREDITS_BALANCE_UPDATED";
public const string _Caption = "USL_ CREDITS_ BALANCE_ UPDATED";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcUSL_FB_UPDATED
{
public const string _Name = "USL_FB_UPDATED";
public const string _Caption = "USL_ FB_ UPDATED";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcUSL_FETCHED_LOCAL_ID
{
public const string _Name = "USL_FETCHED_LOCAL_ID";
public const string _Caption = "USL_ FETCHED_ LOCAL_ ID";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcUSL_FETCHED_LOGON_ID
{
public const string _Name = "USL_FETCHED_LOGON_ID";
public const string _Caption = "USL_ FETCHED_ LOGON_ ID";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcUSL_HAS_BREAKING_NEWS
{
public const string _Name = "USL_HAS_BREAKING_NEWS";
public const string _Caption = "USL_ HAS_ BREAKING_ NEWS";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcUSL_HAS_INBOX
{
public const string _Name = "USL_HAS_INBOX";
public const string _Caption = "USL_ HAS_ INBOX";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcUSL_HAS_ONLINE_FAVORITES
{
public const string _Name = "USL_HAS_ONLINE_FAVORITES";
public const string _Caption = "USL_ HAS_ ONLINE_ FAVORITES";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcUSL_ID
{
public const string _Name = "USL_ID";
public const string _Caption = "USL_ ID";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcUSL_IS_ONLINE
{
public const string _Name = "USL_IS_ONLINE";
public const string _Caption = "USL_ IS_ ONLINE";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcUSL_LINK_UPDATED
{
public const string _Name = "USL_LINK_UPDATED";
public const string _Caption = "USL_ LINK_ UPDATED";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcUSL_SID
{
public const string _Name = "USL_SID";
public const string _Caption = "USL_ SID";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcUSL_USER_ID
{
public const string _Name = "USL_USER_ID";
public const string _Caption = "USL_ USER_ ID";
public const string _ParentName = "APT_USER_LOGONSelectByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,string p_strUSL_SID)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_strUSL_SID);
db.LoadDataSet(cmd, p_ds, p_strTableName);}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,string p_strUSL_SID,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_strUSL_SID);
p_db.LoadDataSet(cmd, p_ds, p_strTableName, p_trn);}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
