//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.SPs
{
public class procPT_USERUpdateUSR_LAT_USR_LNGByUSL_SID
{
public const string _Name = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID";
public const string _Caption = "PT_ USERUpdate USR_ LAT_ USR_ LNGBy USL_ SID";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
string p_strUSL_SID, System.Nullable<decimal> p_decUSR_LAT, System.Nullable<decimal> p_decUSR_LNG)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID";
SqlParameterCollection(cmd.Parameters, p_strUSL_SID, p_decUSR_LAT, p_decUSR_LNG);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSL_SID._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_LAT._SqlParameter());
p_oSqlParameterCollection.Add(parUSR_LNG._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, string p_strUSL_SID, System.Nullable<decimal> p_decUSR_LAT, System.Nullable<decimal> p_decUSR_LNG)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSL_SID._SqlParameter(p_strUSL_SID));
p_oSqlParameterCollection.Add(parUSR_LAT._SqlParameter(p_decUSR_LAT));
p_oSqlParameterCollection.Add(parUSR_LNG._SqlParameter(p_decUSR_LNG));
}
public class parUSL_SID
{
public const string _Name = "@USL_SID";
public const string _Caption = "@ USL_ SID";
public const string _ParentName = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID.DefaultView.[0].@USL_SID";
public const string _BindDataReader = "[@USL_SID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_SID", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USL_SID", 50, -1, 50, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_LAT
{
public const string _Name = "@USR_LAT";
public const string _Caption = "@ USR_ LAT";
public const string _ParentName = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Decimal;
public const Int32 _Length = 9;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID.DefaultView.[0].@USR_LAT";
public const string _BindDataReader = "[@USR_LAT]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_LAT", 18, 12, 9, SqlDbType.Decimal, "decimal", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<decimal> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_LAT", 18, 12, 9, SqlDbType.Decimal, "decimal", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSR_LNG
{
public const string _Name = "@USR_LNG";
public const string _Caption = "@ USR_ LNG";
public const string _ParentName = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID";
public const SqlDbType _SqlDbType = SqlDbType.Decimal;
public const Int32 _Length = 9;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USERUpdateUSR_LAT_USR_LNGByUSL_SID.DefaultView.[0].@USR_LNG";
public const string _BindDataReader = "[@USR_LNG]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_LNG", 18, 12, 9, SqlDbType.Decimal, "decimal", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<decimal> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USR_LNG", 18, 12, 9, SqlDbType.Decimal, "decimal", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUSL_SID : parUSL_SID {}
public class inUSR_LAT : parUSR_LAT {}
public class inUSR_LNG : parUSR_LNG {}
public static int ExecuteNonQuery(
string p_strUSL_SID, System.Nullable<decimal> p_decUSR_LAT, System.Nullable<decimal> p_decUSR_LNG)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_strUSL_SID, p_decUSR_LAT, p_decUSR_LNG);
int iResult = db.ExecuteNonQuery(cmd);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
string p_strUSL_SID, System.Nullable<decimal> p_decUSR_LAT, System.Nullable<decimal> p_decUSR_LNG,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_strUSL_SID, p_decUSR_LAT, p_decUSR_LNG);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
