//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 29/03/2012 14:43
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.Storage.DBS.dbStorageDB.SPs
{
public class procPT_USER_COMMInsertIntoByUSC_USER_ID
{
public const string _Name = "PT_USER_COMMInsertIntoByUSC_USER_ID";
public const string _Caption = "PT_ USER_ COMMInsert Into By USC_ USER_ ID";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_USER_COMMInsertIntoByUSC_USER_ID";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iUSC_COMM_TYPE_CODE, System.Nullable<int> p_iUSC_GETTER_USER_ID, System.Nullable<int> p_iUSC_PRESENT_CODE, string p_strUSC_TEXT, System.Nullable<int> p_iUSC_USER_ID, System.Nullable<int> p_iUSC_WINK_CODE)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "PT_USER_COMMInsertIntoByUSC_USER_ID";
SqlParameterCollection(cmd.Parameters, p_iUSC_COMM_TYPE_CODE, p_iUSC_GETTER_USER_ID, p_iUSC_PRESENT_CODE, p_strUSC_TEXT, p_iUSC_USER_ID, p_iUSC_WINK_CODE);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSC_COMM_TYPE_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSC_GETTER_USER_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSC_PRESENT_CODE._SqlParameter());
p_oSqlParameterCollection.Add(parUSC_TEXT._SqlParameter());
p_oSqlParameterCollection.Add(parUSC_USER_ID._SqlParameter());
p_oSqlParameterCollection.Add(parUSC_WINK_CODE._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iUSC_COMM_TYPE_CODE, System.Nullable<int> p_iUSC_GETTER_USER_ID, System.Nullable<int> p_iUSC_PRESENT_CODE, string p_strUSC_TEXT, System.Nullable<int> p_iUSC_USER_ID, System.Nullable<int> p_iUSC_WINK_CODE)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parUSC_COMM_TYPE_CODE._SqlParameter(p_iUSC_COMM_TYPE_CODE));
p_oSqlParameterCollection.Add(parUSC_GETTER_USER_ID._SqlParameter(p_iUSC_GETTER_USER_ID));
p_oSqlParameterCollection.Add(parUSC_PRESENT_CODE._SqlParameter(p_iUSC_PRESENT_CODE));
p_oSqlParameterCollection.Add(parUSC_TEXT._SqlParameter(p_strUSC_TEXT));
p_oSqlParameterCollection.Add(parUSC_USER_ID._SqlParameter(p_iUSC_USER_ID));
p_oSqlParameterCollection.Add(parUSC_WINK_CODE._SqlParameter(p_iUSC_WINK_CODE));
}
public class parUSC_COMM_TYPE_CODE
{
public const string _Name = "@USC_COMM_TYPE_CODE";
public const string _Caption = "@ USC_ COMM_ TYPE_ CODE";
public const string _ParentName = "PT_USER_COMMInsertIntoByUSC_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USER_COMMInsertIntoByUSC_USER_ID.DefaultView.[0].@USC_COMM_TYPE_CODE";
public const string _BindDataReader = "[@USC_COMM_TYPE_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_COMM_TYPE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_COMM_TYPE_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSC_GETTER_USER_ID
{
public const string _Name = "@USC_GETTER_USER_ID";
public const string _Caption = "@ USC_ GETTER_ USER_ ID";
public const string _ParentName = "PT_USER_COMMInsertIntoByUSC_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USER_COMMInsertIntoByUSC_USER_ID.DefaultView.[0].@USC_GETTER_USER_ID";
public const string _BindDataReader = "[@USC_GETTER_USER_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_GETTER_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_GETTER_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSC_PRESENT_CODE
{
public const string _Name = "@USC_PRESENT_CODE";
public const string _Caption = "@ USC_ PRESENT_ CODE";
public const string _ParentName = "PT_USER_COMMInsertIntoByUSC_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USER_COMMInsertIntoByUSC_USER_ID.DefaultView.[0].@USC_PRESENT_CODE";
public const string _BindDataReader = "[@USC_PRESENT_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_PRESENT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_PRESENT_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSC_TEXT
{
public const string _Name = "@USC_TEXT";
public const string _Caption = "@ USC_ TEXT";
public const string _ParentName = "PT_USER_COMMInsertIntoByUSC_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USER_COMMInsertIntoByUSC_USER_ID.DefaultView.[0].@USC_TEXT";
public const string _BindDataReader = "[@USC_TEXT]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_TEXT", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(string Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_TEXT", 255, -1, 255, SqlDbType.NVarChar, "string", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSC_USER_ID
{
public const string _Name = "@USC_USER_ID";
public const string _Caption = "@ USC_ USER_ ID";
public const string _ParentName = "PT_USER_COMMInsertIntoByUSC_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USER_COMMInsertIntoByUSC_USER_ID.DefaultView.[0].@USC_USER_ID";
public const string _BindDataReader = "[@USC_USER_ID]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_USER_ID", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class parUSC_WINK_CODE
{
public const string _Name = "@USC_WINK_CODE";
public const string _Caption = "@ USC_ WINK_ CODE";
public const string _ParentName = "PT_USER_COMMInsertIntoByUSC_USER_ID";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "PT_USER_COMMInsertIntoByUSC_USER_ID.DefaultView.[0].@USC_WINK_CODE";
public const string _BindDataReader = "[@USC_WINK_CODE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_WINK_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@USC_WINK_CODE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class inUSC_COMM_TYPE_CODE : parUSC_COMM_TYPE_CODE {}
public class inUSC_GETTER_USER_ID : parUSC_GETTER_USER_ID {}
public class inUSC_PRESENT_CODE : parUSC_PRESENT_CODE {}
public class inUSC_TEXT : parUSC_TEXT {}
public class inUSC_USER_ID : parUSC_USER_ID {}
public class inUSC_WINK_CODE : parUSC_WINK_CODE {}
public static int ExecuteNonQuery(
System.Nullable<int> p_iUSC_COMM_TYPE_CODE, System.Nullable<int> p_iUSC_GETTER_USER_ID, System.Nullable<int> p_iUSC_PRESENT_CODE, string p_strUSC_TEXT, System.Nullable<int> p_iUSC_USER_ID, System.Nullable<int> p_iUSC_WINK_CODE)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iUSC_COMM_TYPE_CODE, p_iUSC_GETTER_USER_ID, p_iUSC_PRESENT_CODE, p_strUSC_TEXT, p_iUSC_USER_ID, p_iUSC_WINK_CODE);
int iResult = db.ExecuteNonQuery(cmd);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static int ExecuteNonQuery(
System.Nullable<int> p_iUSC_COMM_TYPE_CODE, System.Nullable<int> p_iUSC_GETTER_USER_ID, System.Nullable<int> p_iUSC_PRESENT_CODE, string p_strUSC_TEXT, System.Nullable<int> p_iUSC_USER_ID, System.Nullable<int> p_iUSC_WINK_CODE,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iUSC_COMM_TYPE_CODE, p_iUSC_GETTER_USER_ID, p_iUSC_PRESENT_CODE, p_strUSC_TEXT, p_iUSC_USER_ID, p_iUSC_WINK_CODE);
int iResult = p_db.ExecuteNonQuery(cmd, p_trn);

return iResult;
}
catch (System.Exception ex)
{
MADA.DatePercent.BB.Storage.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
