//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/03/2012 13:20
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.NLB.DBS.dbNlbDB.SPs
{
public class procAPT_SERVERSelectBySRV_SERVER_TYPE
{
public const string _Name = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const string _Caption = "APT_ SERVERSelect By SRV_ SERVER_ TYPE";

public static SqlCommand SqlCommand()
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_SERVERSelectBySRV_SERVER_TYPE";
SqlParameterCollection(cmd.Parameters);
return cmd;
}
public static SqlCommand SqlCommand(
System.Nullable<int> p_iSRV_SERVER_TYPE)
{
System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand();
cmd.CommandType = CommandType.StoredProcedure;
cmd.CommandText = "APT_SERVERSelectBySRV_SERVER_TYPE";
SqlParameterCollection(cmd.Parameters, p_iSRV_SERVER_TYPE);
return cmd;
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parSRV_SERVER_TYPE._SqlParameter());
}
public static void SqlParameterCollection(
System.Data.SqlClient.SqlParameterCollection p_oSqlParameterCollection
, System.Nullable<int> p_iSRV_SERVER_TYPE)
{
p_oSqlParameterCollection.Clear();
p_oSqlParameterCollection.Add(parSRV_SERVER_TYPE._SqlParameter(p_iSRV_SERVER_TYPE));
}
public class parSRV_SERVER_TYPE
{
public const string _Name = "@SRV_SERVER_TYPE";
public const string _Caption = "@ SRV_ SERVER_ TYPE";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const string _BindDataAdapter = "APT_SERVERSelectBySRV_SERVER_TYPE.DefaultView.[0].@SRV_SERVER_TYPE";
public const string _BindDataReader = "[@SRV_SERVER_TYPE]";
public const ParameterDirection _ParameterDirection = ParameterDirection.Input;
public static SqlParameter _SqlParameter()
{
return DBS.Tools.CreateSqlParameterReferenceType("@SRV_SERVER_TYPE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "");
}
public static SqlParameter _SqlParameter(System.Nullable<int> Value)
{
return DBS.Tools.CreateSqlParameterReferenceType("@SRV_SERVER_TYPE", 10, 0, 4, SqlDbType.Int, "int", ParameterDirection.Input, true, false, "", Value);
}
}
public class inSRV_SERVER_TYPE : parSRV_SERVER_TYPE {}
public class rsAPT_SERVERSelectBySRV_SERVER_TYPE
{
public const string _Name = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const string _Caption = "APT_ SERVERSelect By SRV_ SERVER_ TYPE";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public class slcSRV_DB_CONTROL_PANEL
{
public const string _Name = "SRV_DB_CONTROL_PANEL";
public const string _Caption = "SRV_ DB_ CONTROL_ PANEL";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_DB_COST
{
public const string _Name = "SRV_DB_COST";
public const string _Caption = "SRV_ DB_ COST";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcSRV_DB_DNS
{
public const string _Name = "SRV_DB_DNS";
public const string _Caption = "SRV_ DB_ DNS";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_DB_NAME
{
public const string _Name = "SRV_DB_NAME";
public const string _Caption = "SRV_ DB_ NAME";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_HOST_APP_POOL_URL
{
public const string _Name = "SRV_HOST_APP_POOL_URL";
public const string _Caption = "SRV_ HOST_ APP_ POOL_ URL";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_HOST_CODE
{
public const string _Name = "SRV_HOST_CODE";
public const string _Caption = "SRV_ HOST_ CODE";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcSRV_HOST_CONTROL_PANEL_1
{
public const string _Name = "SRV_HOST_CONTROL_PANEL_1";
public const string _Caption = "SRV_ HOST_ CONTROL_ PANEL_1";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_HOST_CONTROL_PANEL_2
{
public const string _Name = "SRV_HOST_CONTROL_PANEL_2";
public const string _Caption = "SRV_ HOST_ CONTROL_ PANEL_2";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_HOST_COST
{
public const string _Name = "SRV_HOST_COST";
public const string _Caption = "SRV_ HOST_ COST";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcSRV_HOST_LAT
{
public const string _Name = "SRV_HOST_LAT";
public const string _Caption = "SRV_ HOST_ LAT";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Decimal;
public const Int32 _Length = -1;
}
public class slcSRV_HOST_LNG
{
public const string _Name = "SRV_HOST_LNG";
public const string _Caption = "SRV_ HOST_ LNG";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Decimal;
public const Int32 _Length = -1;
}
public class slcSRV_HOST_LOCATION
{
public const string _Name = "SRV_HOST_LOCATION";
public const string _Caption = "SRV_ HOST_ LOCATION";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_HOST_PDF
{
public const string _Name = "SRV_HOST_PDF";
public const string _Caption = "SRV_ HOST_ PDF";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcSRV_ID
{
public const string _Name = "SRV_ID";
public const string _Caption = "SRV_ ID";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcSRV_IS_SSL
{
public const string _Name = "SRV_IS_SSL";
public const string _Caption = "SRV_ IS_ SSL";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = -1;
}
public class slcSRV_REG_CODE
{
public const string _Name = "SRV_REG_CODE";
public const string _Caption = "SRV_ REG_ CODE";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
public class slcSRV_REG_DNS
{
public const string _Name = "SRV_REG_DNS";
public const string _Caption = "SRV_ REG_ DNS";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_REG_DNS_CONTROL_PANEL
{
public const string _Name = "SRV_REG_DNS_CONTROL_PANEL";
public const string _Caption = "SRV_ REG_ DNS_ CONTROL_ PANEL";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_REG_DNS_COST
{
public const string _Name = "SRV_REG_DNS_COST";
public const string _Caption = "SRV_ REG_ DNS_ COST";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
}
public class slcSRV_REG_SUB_DOMAIN_NAME
{
public const string _Name = "SRV_REG_SUB_DOMAIN_NAME";
public const string _Caption = "SRV_ REG_ SUB_ DOMAIN_ NAME";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
}
public class slcSRV_SERVER_TYPE
{
public const string _Name = "SRV_SERVER_TYPE";
public const string _Caption = "SRV_ SERVER_ TYPE";
public const string _ParentName = "APT_SERVERSelectBySRV_SERVER_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = -1;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,System.Nullable<int> p_iSRV_SERVER_TYPE)
{
try
{
Microsoft.Practices.EnterpriseLibrary.Data.Database db = DatabaseFactory.CreateDatabase();
SqlCommand cmd = SqlCommand(p_iSRV_SERVER_TYPE);
db.LoadDataSet(cmd, p_ds, p_strTableName);}
catch (System.Exception ex)
{
MADA.DatePercent.BB.NLB.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
public static void LoadDataSet(System.Data.DataSet p_ds, string p_strTableName,System.Nullable<int> p_iSRV_SERVER_TYPE,Microsoft.Practices.EnterpriseLibrary.Data.Database p_db,System.Data.Common.DbTransaction p_trn)
{
try
{
SqlCommand cmd = SqlCommand(p_iSRV_SERVER_TYPE);
p_db.LoadDataSet(cmd, p_ds, p_strTableName, p_trn);}
catch (System.Exception ex)
{
MADA.DatePercent.BB.NLB.DBS.Tools.WriteToLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
throw;
}
}
}
}
