//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.Tables
{
public class tblT_LINK_TYPE_ENUM
{
public const string _Name = "T_LINK_TYPE_ENUM";
public const string _Caption = "T_ LINK_ TYPE_ ENUM";

public class colLKT_CODE
{
public const string _Name = "LKT_CODE";
public const string _Caption = "LKT_ CODE";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_CODE";
public const string _BindDataReader = "[LKT_CODE]";
}
public class colLKT_DESCRIPTION
{
public const string _Name = "LKT_DESCRIPTION";
public const string _Caption = "LKT_ DESCRIPTION";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_DESCRIPTION";
public const string _BindDataReader = "[LKT_DESCRIPTION]";
}
public class colLKT_LINK_ACTION_TYPE_1
{
public const string _Name = "LKT_LINK_ACTION_TYPE_1";
public const string _Caption = "LKT_ LINK_ ACTION_ TYPE_1";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_LINK_ACTION_TYPE_1";
public const string _BindDataReader = "[LKT_LINK_ACTION_TYPE_1]";
}
public class colLKT_LINK_ACTION_TYPE_2
{
public const string _Name = "LKT_LINK_ACTION_TYPE_2";
public const string _Caption = "LKT_ LINK_ ACTION_ TYPE_2";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_LINK_ACTION_TYPE_2";
public const string _BindDataReader = "[LKT_LINK_ACTION_TYPE_2]";
}
public class colLKT_SMAP_PARAMETER_VISIBLE
{
public const string _Name = "LKT_SMAP_PARAMETER_VISIBLE";
public const string _Caption = "LKT_ SMAP_ PARAMETER_ VISIBLE";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_SMAP_PARAMETER_VISIBLE";
public const string _BindDataReader = "[LKT_SMAP_PARAMETER_VISIBLE]";
}
public class colLKT_SMAP_PARAMETER_VISIBLE_DESCRIPTION
{
public const string _Name = "LKT_SMAP_PARAMETER_VISIBLE_DESCRIPTION";
public const string _Caption = "LKT_ SMAP_ PARAMETER_ VISIBLE_ DESCRIPTION";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_SMAP_PARAMETER_VISIBLE_DESCRIPTION";
public const string _BindDataReader = "[LKT_SMAP_PARAMETER_VISIBLE_DESCRIPTION]";
}
public class colLKT_SMAP_PARAMETER_VISIBLE_ORDER_BY
{
public const string _Name = "LKT_SMAP_PARAMETER_VISIBLE_ORDER_BY";
public const string _Caption = "LKT_ SMAP_ PARAMETER_ VISIBLE_ ORDER_ BY";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_SMAP_PARAMETER_VISIBLE_ORDER_BY";
public const string _BindDataReader = "[LKT_SMAP_PARAMETER_VISIBLE_ORDER_BY]";
}
public class colLKT_SRC
{
public const string _Name = "LKT_SRC";
public const string _Caption = "LKT_ SRC";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_SRC";
public const string _BindDataReader = "[LKT_SRC]";
}
public class colLKT_TEXT
{
public const string _Name = "LKT_TEXT";
public const string _Caption = "LKT_ TEXT";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 255;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].LKT_TEXT";
public const string _BindDataReader = "[LKT_TEXT]";
}
public class colValueCode
{
public const string _Name = "ValueCode";
public const string _Caption = "Value Code";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = true;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].ValueCode";
public const string _BindDataReader = "[ValueCode]";
}
public class colValueName
{
public const string _Name = "ValueName";
public const string _Caption = "Value Name";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = true;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].ValueName";
public const string _BindDataReader = "[ValueName]";
}
public class colValueNameEnum
{
public const string _Name = "ValueNameEnum";
public const string _Caption = "Value Name Enum";
public const string _Description = "";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_LINK_TYPE_ENUM.DefaultView.[0].ValueNameEnum";
public const string _BindDataReader = "[ValueNameEnum]";
}
public class idxPK_T_STS
{
public const string _Name = "PK_T_STS";
public const string _Caption = "PK_ T_ STS";
public const string _ParentName = "T_LINK_TYPE_ENUM";
public const bool _IsPrimaryKey = true;

public class ixcLKT_CODE : colLKT_CODE {}
}
public class pkxPK_T_STS : idxPK_T_STS {}
}
}
