//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.Tables
{
public class tblT_MAX_MIND_TRACKING
{
public const string _Name = "T_MAX_MIND_TRACKING";
public const string _Caption = "T_ MAX_ MIND_ TRACKING";

public class colMIP_ID
{
public const string _Name = "MIP_ID";
public const string _Caption = "MIP_ ID";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_ID";
public const string _BindDataReader = "[MIP_ID]";
}
public class colMIP_REQUEST_DATETIME
{
public const string _Name = "MIP_REQUEST_DATETIME";
public const string _Caption = "MIP_ REQUEST_ DATETIME";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.DateTime;
public const Int32 _Length = 8;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_REQUEST_DATETIME";
public const string _BindDataReader = "[MIP_REQUEST_DATETIME]";
}
public class colMIP_REQUEST_IP
{
public const string _Name = "MIP_REQUEST_IP";
public const string _Caption = "MIP_ REQUEST_ IP";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_REQUEST_IP";
public const string _BindDataReader = "[MIP_REQUEST_IP]";
}
public class colMIP_REQUEST_URI
{
public const string _Name = "MIP_REQUEST_URI";
public const string _Caption = "MIP_ REQUEST_ URI";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_REQUEST_URI";
public const string _BindDataReader = "[MIP_REQUEST_URI]";
}
public class colMIP_RESPONSE_LAT
{
public const string _Name = "MIP_RESPONSE_LAT";
public const string _Caption = "MIP_ RESPONSE_ LAT";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.Decimal;
public const Int32 _Length = 9;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_RESPONSE_LAT";
public const string _BindDataReader = "[MIP_RESPONSE_LAT]";
}
public class colMIP_RESPONSE_LNG
{
public const string _Name = "MIP_RESPONSE_LNG";
public const string _Caption = "MIP_ RESPONSE_ LNG";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.Decimal;
public const Int32 _Length = 9;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_RESPONSE_LNG";
public const string _BindDataReader = "[MIP_RESPONSE_LNG]";
}
public class colMIP_RESPONSE_STREAM
{
public const string _Name = "MIP_RESPONSE_STREAM";
public const string _Caption = "MIP_ RESPONSE_ STREAM";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 0;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_RESPONSE_STREAM";
public const string _BindDataReader = "[MIP_RESPONSE_STREAM]";
}
public class colMIP_RESULT
{
public const string _Name = "MIP_RESULT";
public const string _Caption = "MIP_ RESULT";
public const string _Description = "";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_MAX_MIND_TRACKING.DefaultView.[0].MIP_RESULT";
public const string _BindDataReader = "[MIP_RESULT]";
}
public class idcMIP_ID : colMIP_ID {}
public class idxPK_T_MAX_MIND_TRACKING
{
public const string _Name = "PK_T_MAX_MIND_TRACKING";
public const string _Caption = "PK_ T_ MAX_ MIND_ TRACKING";
public const string _ParentName = "T_MAX_MIND_TRACKING";
public const bool _IsPrimaryKey = true;

public class ixcMIP_ID : colMIP_ID {}
}
public class pkxPK_T_MAX_MIND_TRACKING : idxPK_T_MAX_MIND_TRACKING {}
}
}
