//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.Tables
{
public class tblT_PROP_WEIGHT_TYPE
{
public const string _Name = "T_PROP_WEIGHT_TYPE";
public const string _Caption = "T_ PROP_ WEIGHT_ TYPE";

public class colWGT_CODE
{
public const string _Name = "WGT_CODE";
public const string _Caption = "WGT_ CODE";
public const string _Description = "";
public const string _ParentName = "T_PROP_WEIGHT_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_PROP_WEIGHT_TYPE.DefaultView.[0].WGT_CODE";
public const string _BindDataReader = "[WGT_CODE]";
}
public class colWGT_DESCRIPTION
{
public const string _Name = "WGT_DESCRIPTION";
public const string _Caption = "WGT_ DESCRIPTION";
public const string _Description = "";
public const string _ParentName = "T_PROP_WEIGHT_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_PROP_WEIGHT_TYPE.DefaultView.[0].WGT_DESCRIPTION";
public const string _BindDataReader = "[WGT_DESCRIPTION]";
}
public class colWGT_DESCRIPTION_IMPERIAL
{
public const string _Name = "WGT_DESCRIPTION_IMPERIAL";
public const string _Caption = "WGT_ DESCRIPTION_ IMPERIAL";
public const string _Description = "";
public const string _ParentName = "T_PROP_WEIGHT_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_PROP_WEIGHT_TYPE.DefaultView.[0].WGT_DESCRIPTION_IMPERIAL";
public const string _BindDataReader = "[WGT_DESCRIPTION_IMPERIAL]";
}
public class colWGT_DESCRIPTION_METRIC
{
public const string _Name = "WGT_DESCRIPTION_METRIC";
public const string _Caption = "WGT_ DESCRIPTION_ METRIC";
public const string _Description = "";
public const string _ParentName = "T_PROP_WEIGHT_TYPE";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 50;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_PROP_WEIGHT_TYPE.DefaultView.[0].WGT_DESCRIPTION_METRIC";
public const string _BindDataReader = "[WGT_DESCRIPTION_METRIC]";
}
public class idxPK_T_WEIGHT_TYPE
{
public const string _Name = "PK_T_WEIGHT_TYPE";
public const string _Caption = "PK_ T_ WEIGHT_ TYPE";
public const string _ParentName = "T_PROP_WEIGHT_TYPE";
public const bool _IsPrimaryKey = true;

public class ixcWGT_CODE : colWGT_CODE {}
}
public class pkxPK_T_WEIGHT_TYPE : idxPK_T_WEIGHT_TYPE {}
}
}
