//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.Tables
{
public class tblT_TRANSLATION
{
public const string _Name = "T_TRANSLATION";
public const string _Caption = "T_ TRANSLATION";

public class colTRN_CODE
{
public const string _Name = "TRN_CODE";
public const string _Caption = "TRN_ CODE";
public const string _Description = "";
public const string _ParentName = "T_TRANSLATION";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 200;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_TRANSLATION.DefaultView.[0].TRN_CODE";
public const string _BindDataReader = "[TRN_CODE]";
}
public class colTRN_CULTURE_ID
{
public const string _Name = "TRN_CULTURE_ID";
public const string _Caption = "TRN_ CULTURE_ ID";
public const string _Description = "";
public const string _ParentName = "T_TRANSLATION";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_TRANSLATION.DefaultView.[0].TRN_CULTURE_ID";
public const string _BindDataReader = "[TRN_CULTURE_ID]";
}
public class colTRN_TRANSLATION
{
public const string _Name = "TRN_TRANSLATION";
public const string _Caption = "TRN_ TRANSLATION";
public const string _Description = "";
public const string _ParentName = "T_TRANSLATION";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_TRANSLATION.DefaultView.[0].TRN_TRANSLATION";
public const string _BindDataReader = "[TRN_TRANSLATION]";
}
public class idxPK_T_TRANSLATION
{
public const string _Name = "PK_T_TRANSLATION";
public const string _Caption = "PK_ T_ TRANSLATION";
public const string _ParentName = "T_TRANSLATION";
public const bool _IsPrimaryKey = true;

public class ixcTRN_CODE : colTRN_CODE {}
public class ixcTRN_CULTURE_ID : colTRN_CULTURE_ID {}
}
public class pkxPK_T_TRANSLATION : idxPK_T_TRANSLATION {}
}
}
