//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.Tables
{
public class tblT_USER_PROP_INTERESTS
{
public const string _Name = "T_USER_PROP_INTERESTS";
public const string _Caption = "T_ USER_ PROP_ INTERESTS";

public class colUIT_ID
{
public const string _Name = "UIT_ID";
public const string _Caption = "UIT_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_PROP_INTERESTS";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_USER_PROP_INTERESTS.DefaultView.[0].UIT_ID";
public const string _BindDataReader = "[UIT_ID]";
}
public class colUIT_PROP_INTERESTS_CODE
{
public const string _Name = "UIT_PROP_INTERESTS_CODE";
public const string _Caption = "UIT_ PROP_ INTERESTS_ CODE";
public const string _Description = "";
public const string _ParentName = "T_USER_PROP_INTERESTS";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_PROP_INTERESTS.DefaultView.[0].UIT_PROP_INTERESTS_CODE";
public const string _BindDataReader = "[UIT_PROP_INTERESTS_CODE]";
}
public class colUIT_USER_ID
{
public const string _Name = "UIT_USER_ID";
public const string _Caption = "UIT_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_PROP_INTERESTS";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_PROP_INTERESTS.DefaultView.[0].UIT_USER_ID";
public const string _BindDataReader = "[UIT_USER_ID]";
}
public class idcUIT_ID : colUIT_ID {}
public class idxIX_T_USER_PROP_INTERESTS_UIT_USER_ID
{
public const string _Name = "IX_T_USER_PROP_INTERESTS_UIT_USER_ID";
public const string _Caption = "IX_ T_ USER_ PROP_ INTERESTS_ UIT_ USER_ ID";
public const string _ParentName = "T_USER_PROP_INTERESTS";
public const bool _IsPrimaryKey = false;

public class ixcUIT_USER_ID : colUIT_USER_ID {}
}
public class idxPK_T_USER_PROP_INTERESTS
{
public const string _Name = "PK_T_USER_PROP_INTERESTS";
public const string _Caption = "PK_ T_ USER_ PROP_ INTERESTS";
public const string _ParentName = "T_USER_PROP_INTERESTS";
public const bool _IsPrimaryKey = true;

public class ixcUIT_ID : colUIT_ID {}
}
public class pkxPK_T_USER_PROP_INTERESTS : idxPK_T_USER_PROP_INTERESTS {}
}
}
