//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the Database Schema tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
//
//     Exception should be handled in a higher layer.
//
//     generation time: 27/12/2011 08:42
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace MADA.DatePercent.BB.WL.DBS.dbDatePercentDB20.Tables
{
public class tblT_USER_PHOTO
{
public const string _Name = "T_USER_PHOTO";
public const string _Caption = "T_ USER_ PHOTO";

public class colUPH_ID
{
public const string _Name = "UPH_ID";
public const string _Caption = "UPH_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_PHOTO";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = true;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = true;
public const string _BindDataAdapter = "T_USER_PHOTO.DefaultView.[0].UPH_ID";
public const string _BindDataReader = "[UPH_ID]";
}
public class colUPH_IO_ERROR
{
public const string _Name = "UPH_IO_ERROR";
public const string _Caption = "UPH_ IO_ ERROR";
public const string _Description = "";
public const string _ParentName = "T_USER_PHOTO";
public const SqlDbType _SqlDbType = SqlDbType.Bit;
public const Int32 _Length = 1;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_PHOTO.DefaultView.[0].UPH_IO_ERROR";
public const string _BindDataReader = "[UPH_IO_ERROR]";
}
public class colUPH_ORIGINAL_URL
{
public const string _Name = "UPH_ORIGINAL_URL";
public const string _Caption = "UPH_ ORIGINAL_ URL";
public const string _Description = "";
public const string _ParentName = "T_USER_PHOTO";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_PHOTO.DefaultView.[0].UPH_ORIGINAL_URL";
public const string _BindDataReader = "[UPH_ORIGINAL_URL]";
}
public class colUPH_SMALL_URL
{
public const string _Name = "UPH_SMALL_URL";
public const string _Caption = "UPH_ SMALL_ URL";
public const string _Description = "";
public const string _ParentName = "T_USER_PHOTO";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_PHOTO.DefaultView.[0].UPH_SMALL_URL";
public const string _BindDataReader = "[UPH_SMALL_URL]";
}
public class colUPH_THUMB_URL
{
public const string _Name = "UPH_THUMB_URL";
public const string _Caption = "UPH_ THUMB_ URL";
public const string _Description = "";
public const string _ParentName = "T_USER_PHOTO";
public const SqlDbType _SqlDbType = SqlDbType.NVarChar;
public const Int32 _Length = 2000;
public const bool _IsNullable = true;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_PHOTO.DefaultView.[0].UPH_THUMB_URL";
public const string _BindDataReader = "[UPH_THUMB_URL]";
}
public class colUPH_USER_ID
{
public const string _Name = "UPH_USER_ID";
public const string _Caption = "UPH_ USER_ ID";
public const string _Description = "";
public const string _ParentName = "T_USER_PHOTO";
public const SqlDbType _SqlDbType = SqlDbType.Int;
public const Int32 _Length = 4;
public const bool _IsNullable = false;
public const bool _IsIdentity = false;
public const bool _IsComputed = false;
public const bool _IsPrimaryKey = false;
public const string _BindDataAdapter = "T_USER_PHOTO.DefaultView.[0].UPH_USER_ID";
public const string _BindDataReader = "[UPH_USER_ID]";
}
public class idcUPH_ID : colUPH_ID {}
public class idxIX_T_USER_PHOTO_UPH_USER_ID
{
public const string _Name = "IX_T_USER_PHOTO_UPH_USER_ID";
public const string _Caption = "IX_ T_ USER_ PHOTO_ UPH_ USER_ ID";
public const string _ParentName = "T_USER_PHOTO";
public const bool _IsPrimaryKey = false;

public class ixcUPH_USER_ID : colUPH_USER_ID {}
}
public class idxPK_T_USER_PHOTO
{
public const string _Name = "PK_T_USER_PHOTO";
public const string _Caption = "PK_ T_ USER_ PHOTO";
public const string _ParentName = "T_USER_PHOTO";
public const bool _IsPrimaryKey = true;

public class ixcUPH_ID : colUPH_ID {}
}
public class pkxPK_T_USER_PHOTO : idxPK_T_USER_PHOTO {}
}
}
